### ISSUE TITLE
How I can use ES7 ?

### ISSUE THREAD

**Issue by scherebedov** [insin/nwb#100]
Hi. How I understand, now I can  using only ES6 or ES5, but I need in ES7. How I can do it ? Thanks.

**Comment by insin** [comment]
Use Babel 5's  `stage: 0` config to enable the experimental proposals it supports: https://github.com/insin/nwb/blob/master/docs/Configuration.md#babel-object

**Comment by scherebedov** [comment]
@insin, Thank you!
