### ISSUE TITLE
React v15 production builds failing with npm3 because a broken version of babel-runtime gets installed into require() scope

### ISSUE THREAD

**Issue by insin** [insin/nwb#101]
The Travis build for npm3 is currently failing because `babel-runtime` is now a transitive dependency of React v15 and npm3 moves it right up into `require()` scope, so the current approach of using Webpack's fallback config never gets a chance to fall back for projects which need `optional: ['runtime']`.

I filed a bug on Babel's issue tracker as every version of babel-runtime post 5.8.29 has a broken `typeof-react-element.js` module, which breaks nwb's production builds: https://phabricator.babeljs.io/T7288

**Comment by varandpez** [comment]
I installed `npm install babel-runtime@5.8.38` to my project that is consuming `nwb

**Comment by insin** [comment]
I fixed this in the test `async/await` project by adding babel-runtime@5.8.29 to its dependencies - I'll add a note about this for npm3 users before releasing the next version.

**Comment by varandpez** [comment]
Noticed that, but surprisingly I was experiencing the issue with v5.8.29, since `nwb` is using the same version. v5.8.38 (the latest by today) is ok.

**Comment by slmgc** [comment]
@insin I also experienced this issue with broken babel-runtime, installing v5.8.38 fixed it.

**Comment by insin** [comment]
Which version of Node.js are you using? `babel-runtime` is no longer a transitive dependency as of <unknown version of `fbjs`>.

**Comment by slmgc** [comment]
@insin react@15.1.0. Yeah, looks like you are right: babel-runtime@5.8.38 fixed the issue with development build, but broke the production build. Adding babel-runtime@5.8.29 to the project fixed the issue, thanks!
