### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by BurntCaramel** [insin/nwb#102]
Sorry if this has already been brought up, but searching for '15' in issues here finds nothing. Is React 15 supported with the current version on npm, or is this coming?

I tried changing the peer and dev dependencies to `"react": "15.0.x"`. But it fails on Travis CI:

```
9.54s$ npm install codecov.io coveralls
npm WARN package.json react-dogear@0.1.1 No repository field.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.4.4/bin/node" "/home/travis/.nvm/versions/node/v4.4.4/bin/npm" "install" "codecov.io" "coveralls"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package react@0.14.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
```

**Comment by insin** [comment]
Try deleting the cache for your Travis build, as it looks like it's failing in the pre-install setup.

There's nothing that specifically needs to be done in nwb itself to support React 15, but there currently issues if you use npm3 and your project uses `optional: ['runtime']` Babel config (see #101) 

I was going to make 0.10 a quick release to install React 15 by default for new projects until this tripped me up.

**Comment by BurntCaramel** [comment]
Ah great that fixed it! Thanks for your help! And thanks for the great tool!
