### ISSUE TITLE
Question. github pages, npm integration?

### ISSUE THREAD

**Issue by mukeshsoni** [insin/nwb#11]
Are you planning to add commands for publishing to github pages and publishing to npm like done by jed Watson's react component generator (https://github.com/JedWatson/generator-react-component)?

**Comment by insin** [comment]
Yes, I've just not done any of that myself before, which is why it isn't in the initial version - this is extracted from about 6 of my projects which had near-identical configuration.

**Comment by mukeshsoni** [comment]
ok, thanks! will try it out.

**Comment by insin** [comment]
Thinking about this, the details of these tasks are irrelevant to what nwb does, and making a choice on your behalf on some of those details will make it less appealing to some.

An earlier version used to also include its own ESLint settings, which would make it a non-starter for many people.

Are there any standalone tools people can install - which specifically deal with these tasks - which you'd recommend?

**Comment by insin** [comment]
Closing this are there are no current plans to integrate these kinds of tools  but will document using them if there are recommendations which look good.
