### ISSUE TITLE
EventSource polyfill breaks IE < 10

### ISSUE THREAD

**Issue by slmgc** [insin/nwb#116]
Hi!

The EventSource polyfill used in nwb is broken for IE < 10, so it's not very convenient to test apps in a development mode in old IE.

I have created a pull-request with the fix for this issue, but I'm not sure whether the EventSource author will update the library anytime soon.

So, my question is:
Is there any particular reason to use the current polyfill for EventSource https://github.com/amvtek/EventSource with 60+ stars instead of, for example, this one https://github.com/Yaffle/EventSource with 800+ stars?

**Comment by insin** [comment]
No particular reason, happy to drop the other implementation in if it works in older IE.

**Comment by slmgc** [comment]
@insin great! I'll test other implementation with old IE.

**Comment by slmgc** [comment]
@insin strangely enough, I can't reproduce this issue anymore. Nevertheless, switching to a more popular EventSource polyfill library seems like a good idea. I've checked it in IE9, works fine.
