### ISSUE TITLE
0.11 RC

### ISSUE THREAD

**Issue by insin** [insin/nwb#117]
```
npm install -g nwb@next
```

**Comment by insin** [comment]
It looks like we need to create our own instance of `chalk` - its `enabled` flag is global and something seems to be disabling it.

**Comment by insin** [comment]
Whoops, forgot I had ericclemmons/npm-install-webpack-plugin#52 patched locally in my nwb repo.

**Comment by ericclemmons** [comment]
@insin I'd love to know a better approach to logging in that plugin!
