### ISSUE TITLE
How can we make Enzyme part of the default testing config for React?

### ISSUE THREAD

**Issue by insin** [insin/nwb#119]
Related Twitter thread: https://twitter.com/jbscript/status/740949154264813569

**Comment by insin** [comment]
Related Twitter thread: https://twitter.com/jbscript/status/740949154264813569

----
**First thoughts:**
I've tried to avoid nwb needing to have React in `dependencies` (which is why [redbox-noreact](https://github.com/insin/redbox-noreact) exists)

----
**Second thoughts:**
Why?

----
**First thoughts:**
Enzyme has a `peerDependency` on React, which makes it problematic to include in a global install of nwb (and for a local install when using nwb for non-React projects, which will generate peerDependency installation or warnings depending on your version of npm).

-----
**Second thoughts:**
Why is it problematic for a global install?
So what if non-React projects pull in another few React dependencies?
There are already a bunch of React-specific dependencies - shouldn't these be split out into a separate `nwb-react` module which gets included in React project skeletons?
```
    "babel-plugin-react-display-name": "2.0.0",
    "babel-plugin-react-transform": "1.1.1",
    "react-transform-catch-errors": "1.0.2",
    "react-transform-hmr": "1.0.4",
    "redbox-noreact": "1.1.0",
```

----
**First thoughts:**
Having different versions of React installed locally and globally opens up the possibility of having two different versions of React in play - a global Enzyme dependency will resolve nwb's version of React first.

----
**Third thoughts:**
Is this really an effective way to find out why you've done things the way you've done them?
Get some sleep

*To be continued....*

**Comment by caseybaggz** [comment]
Can this be closed since we now have the config settings? Seems to work fine for me?

nwb.config:
```
compat: {
    enzyme: true
 }
```

**Comment by insin** [comment]
Enzyme now requires you to configure an adapter rather than needing Webpack workarounds when importing it in your tests: https://github.com/airbnb/enzyme/blob/master/docs/installation/react-16.md
