### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by insin** [insin/nwb#12]
**Dependencies**

- [x] Publish development version of [deduped-babel-presets](https://github.com/insin/deduped-babel-presets) to npm
- [x] Update all dependencies to their Babel 6 versions

**nwb**

- [x] Get nwb itself building and testing with Babel 6 using presets from deduped-babel-presets

**User config**

- [x] Validate that `babel.stage` is either `0-3` or falsy when provided
- [x] Warn if a `babel.loose` string is present in 0.12 config and treat it as its boolean equivalent
- [x] Support a `babel.runtime` flag or string to include the transform runtime plugin

**Babel config generation**

Generate Babel 6 config using deduped-babel-config presets based on build and user config

- [x] Support `stage` number user config as per Babel 5 and use it to choose presets.
- [x] Support `loose` as boolean user config to use an ES2015 `-loose` config from deduped-babel-presets
- [x] Support `native` boolean build config to to use an ES2015 `-native` config from deduped-babel-presets
- [x] Support `presets` list of strings build config to to use additional named presets from deduped-babel-presets
- [x] Support `runtime`to use the runtime transform and choose which features to enable

**Build config**

- [x] Configure Babel build config for React development builds
- [x] Configure Babel build config for React production builds (taking `--preact` into account)
- [X] Enable the 'react' preset by default for module and UMD builds for JSX transforms when needed (hashtag YOLO)
- [x] Use generated Babel config with `babel-loader` when generating Webpack config
- [x] Update Karma config generation to use `babel-polyfill`

**Other**

- [x] Update tests
- [x] Update docs

(Was: Waiting for https://github.com/gaearon/babel-plugin-react-transform/pull/50)

**Comment by insin** [comment]
Reference commit from react-heatpack: https://github.com/insin/react-heatpack/commit/6108dbe409f6f7fd7dbf6d910f61d57d5cad007e

**Comment by insin** [comment]
Reference for what we'll have to do behind the scenes to keep supporting Babel 5 style `loose: 'all'` config: https://github.com/bkonkle/babel-preset-es2015-loose/blob/master/index.js

**Comment by DenysStoianov** [comment]
@insin What about this article? http://www.2ality.com/2015/12/babel6-loose-mode.html

**Comment by insin** [comment]
Here's the start of a potential solution for Babel 6's npm2 problem for nwb: https://github.com/insin/nwb-babel-presets

**Comment by TimonVS** [comment]
What's the progress on this issue? Is there something I can do to contribute?

**Comment by insin** [comment]
Working on it in the `next` branch, using #31 as a reference, but haven't created anything commit-worthy yet.

**Comment by insin** [comment]
Implemented in 0.12.0
