### ISSUE TITLE
Sass files can not be directly required from node_modules

### ISSUE THREAD

**Issue by arddor** [insin/nwb#129]
When trying to require a scss file directly from node_modules `import "../node_modules/bootstrap/scss/bootstrap.scss"` it gives the following error:
```
ERROR in /Users/User/.node/lib/~/nwb/~/css-loader?importLoaders=1!/Users/User/.node/lib/~/nwb/~/postcss-loader?pack=vendor-sass!./~/sass-loader!./~/bootstrap/scss/bootstrap.scss
Module build failed: Error: PostCSS plugin pack is not defined in options
    at Object.module.exports (/Users/User/.node/lib/node_modules/nwb/node_modules/postcss-loader/index.js:41:19)
 @ ./~/bootstrap/scss/bootstrap.scss 4:14-263 13:2-17:4 14:20-269
```
For bootstrap the work around is to define a scss file and there import it. However for every library which imports .scss files directly it will result in the error above, e.g., react-toolbox

**Comment by insin** [comment]
Fixed in v0.11.1
