### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by appjitsu** [insin/nwb#134]
What is the recommended way to deploy to a React app generated with nwb to heroku?

**Comment by lachlanjc** [comment]
@appjitsu Heroku is really not the best place to host an nwb project. nwb produces a set of static files, and Heroku is for apps with dynamic servers on the backend, not static files to run in a browser. Instead, you can push to [GitHub Pages](https://pages.github.com/), [Amazon S3](https://aws.amazon.com/s3/), [Firebase Hosting](https://firebase.google.com/docs/hosting/), etc. For example: in one of my [projects](https://nrafunded.us), I use the [gh-pages package](https://www.npmjs.com/package/gh-pages) and an npm script to deploy my site: https://github.com/lachlanjc/nrafunded/blob/master/package.json#L10

**Comment by ntwcklng** [comment]
An awesome alternative for hosting static website is `now`. You can install it via `npm install -g now` and simply run `npm run build && now /dist` inside your project folder. ([Example](https://dist-qzvimnghaq.now.sh))
More information: [https://github.com/zeit/now-cli](https://github.com/zeit/now-cli)
