### ISSUE TITLE
eject command

### ISSUE THREAD

**Issue by bjrmatos** [insin/nwb#135]
i think it will be very useful to have something like `npm run eject` [create-react-app](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup).

what do you think?

**Comment by insin** [comment]
Yes, useful, but also difficult to get to from where nwb is now.

**Comment by insin** [comment]
Closing this as I don't think it's suitable for nwb, as I'd rather make something configurable than have to eject.
