### ISSUE TITLE
Alias to pre-built react and react-dom in development mode

### ISSUE THREAD

**Issue by insin** [insin/nwb#139]
Good idea from facebookincubator/create-react-app#164 to increase development perf by reducing the number of modules.

Would need to check it with a few apps too see if anyone is replying on deep imports from the react package, and will the way the dist version of `react-dom` loads `react` work as expected?

``` js
{
  resolve: {
    alias: {
      'react': 'react/dist/react.js',
      'react-dom': 'react-dom/dist/react-dom.js'
    }
  }
}
```

[`NormalModuleReplacementPlugin`](https://webpack.github.io/docs/list-of-plugins.html#normalmodulereplacementplugin) is also an option if there are any problems.

I know off-hand that Enzyme would need `react-dom/serve` aliased too, while `react-addons-test-utils` is just a deep import into `react/lib/ReactTestUtils`, but this config would initially only be happening when running a hot-reloading development server.

**Comment by Restuta** [comment]
I use this in prod and there is little caveat. Just setting alias won't improve performance, it also should be added to 'noParse' and to make it work with reactDom or Router `imports` loader has to be used:
```
    /* tells webpack to skip parsing following libraries
     requires use of "import loader" for certain modules, based on https://github.com/christianalfoni/react-webpack-cookbook/issues/30
    */
    noParse: [ pathToReact, pathToReactDom, pathToReactRouter ], 
    loaders: [{
      test: pathToReactDOM,
      loader: 'imports'
    }, {
      test: pathToReactRouter,
      loader: 'imports'
    }, {....
```

**Comment by insin** [comment]
This isn't needed any more - [React now publishes development and production bundles](https://unpkg.com/react/)
