### ISSUE TITLE
Disabling demo builds

### ISSUE THREAD

**Issue by loklaan** [insin/nwb#155]
Hi there,

Just wanted to see if there was interest or acceptance for the idea of adding config to turn off production builds of Demo in `react-component` type?

I bring this up, because a project I am putting together has a consolidated Styleguide for demo'ing components. However, during dev, the demo environment is very useful. But I don't need it past `npm start`. That's my use case, which might not be that uncommon.

**Comment by insin** [comment]
I wouldn't be averse to that, sounds reasonable.

We probably also need something to disable wrapping of `propTypes` with an environment check, as some people have use cases where they want to use `propTypes` in production (e.g. React Bootstrap uses them to mask props, someone builds a UI lib with nwb might want to do likewise).

Still not sure of the cleanest way to configure all these off toggle for default features. I added a [`polyfill` toggle to the top-level config object](https://github.com/insin/nwb/blob/3c5bb94579087cd4e293023ee90daa4e4672c9ac/src/createWebpackConfig.js#L643) to prevent the new default polyfills being added, wondering how ugly that gets as you increase the  number default features you can turn off.

**Comment by insin** [comment]
What do you think of making these all command-line feature toggles?

We already have some precedent with `--preact` (enable experimental build), `--install` (enable experimental dev tooling), `--fallback` (enable fallback serving for HTML5 History apps) and `--reload` (tweak hot reload config), none of which have any config file equivalent.

Potential new toggles:

`react-component` projects:
- `--no-demo[-build]`- turn demo build off
- `--no-[wrap-]proptypes` - turns proptype environment check wrapping off

`react-app`/`web-app` projects:
- `--no-polyfill` - turns off inclusion of default polyfills
- `--no-vendor[-bundle]` - turn off automatic vendor bundle for anything from `node_modules` (replacing the `vendorBundle` config added for this)

**Comment by loklaan** [comment]
I like your reasoning for cli toggles vs config file options.

Thanks for the validation _and_ going ahead to implement it!
