### ISSUE TITLE
UglifyJs encounters SyntaxError

### ISSUE THREAD

**Issue by brumm** [insin/nwb#160]
Hey @insin,

I'm running into an error when trying to build an app which imports https://github.com/Cu3PO42/electron-ipc-tunnel:

```
SyntaxError: Unexpected token: name (IpcClient) [./~/electron-ipc-tunnel/client.js:11,0]
electron/ doesn't exist
```

`nwb serve` is working without problems, only  `nwb build` fails :(

test repo with minimal nwb react-app which reproduces the issue is here: https://github.com/brumm/test

Env:
```
Darwin 15.6.0
node v5.3.0
npm  v3.3.12
```

**Comment by insin** [comment]
It looks like this module has [published untranspiled ES6 to npm](https://npmcdn.com/electron-ipc-tunnel@3.1.0/client.js), which as far as I'm aware isn't supported by UglifyJS yet.

Not that it seems to make a difference in this case, but is the extra [`target` config](https://webpack.github.io/docs/configuration.html#target) value valid?

**Comment by brumm** [comment]
Dang, I should probably have spotted this myself. Thanks for pointing me in the right direction!

>Not that it seems to make a difference in this case, but is the extra target config value valid?

Yeah, it's just not documented (yet?)
https://github.com/webpack/webpack/blob/314c897682b556845fea36d329de8016d1740900/lib/WebpackOptionsApply.js#L154

**Comment by insin** [comment]
Do people generally compress code for Electon apps? It should be possible to disable use of uglify if Node v4 is the target.

**Comment by brumm** [comment]
Awesome! I tried to do this via the individual options `mangle: false` and `compress: false` but that didn't work.

**Comment by xuopled** [comment]
I have also a problem with this `UglifyJS` version with the [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) lib. See [here](https://github.com/algolia/react-element-to-jsx-string/issues/90#issuecomment-319066779)

@insin There is an es6 version of `UglifyJS2` on the [harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony). 

Could you consider use it?
