### ISSUE TITLE
Single page application with nwb/express middleware

### ISSUE THREAD

**Issue by tomitrescak** [insin/nwb#163]
Thanks for this amazing project! How do I setup a single page application when I am using my own express? I used your example app as a starting point, I am just not sure how to configure express to serve the initial page from every url.

This is what I have:

```js
try {
    fs.statSync('dist');
    console.log('Serving static build from dist/');
    console.log('Run `npm run clean` to return to development mode');
    app.use('/', express.static(path.join(__dirname, 'dist')));
    
     // THIS IS POTENTIALLY OK
    app.get('*', function (req, res) {
      res.sendFile(path.join(__dirname, 'dist', 'index.html');
    });
  } catch (e) {
    console.log('Serving development build with nwb middleware');
    console.log('Run `npm run build` to create a production build');
    app.use(require('nwb/express')(express));

    // BUT WHAT TO DO HERE ???
    app.get('*', function (req, res) {
      res.sendFile( ... which path ... );
    });
  }
```

**Comment by tomitrescak** [comment]
I even tried adding the fallback-history api and no luck.

```
import * as historyAPIFallback from 'connect-history-api-fallback';

...
app.use(historyAPIFallback()); // still no luck
```

**Comment by insin** [comment]
I use the history fallback middleware in different places depending on whether or not it's a development or production build being served.

The fallback middleware just changes the incoming request path to `/index.html`, so you need to have it before you either use nwb middleware (which serves `/index.html`) or static middleware.

I don't have any examples handy, but I can provide one when I get into work on Monday if you've not cracked it by then :smile_cat:

**Comment by tomitrescak** [comment]
Thanks! Yes moving it before the middleware deifnitely helped.
