### ISSUE TITLE
Hot reloading pure/stateless react components

### ISSUE THREAD

**Issue by tomitrescak** [insin/nwb#164]
Hi, is there a possibility to hot reload pure/stateless react components? Thanks.

**Comment by insin** [comment]
They should work once nwb is upgraded to use React Hot Loader v3 (#99)

**Comment by tomitrescak** [comment]
Is there any way I can achieve it now? I've tried to modify my webpack config to reflect the v.3 requirements, but it seem the previous version keeps kicking in.

**Comment by insin** [comment]
As of v0.16.0 you can pass a `--no-hmre` flag to `nwb serve...` commands to disable use of React Transform-based HMR patching so you can implement your own.

Closing this in favour of the RHL v3 issue.
