### ISSUE TITLE
Compatibility config for the AWS SDK

### ISSUE THREAD

**Issue by insin** [insin/nwb#165]
Add `aws` support to `webpack.compat`.

See https://github.com/aws/aws-sdk-js/issues/603#issuecomment-235506094 for config to try.

**Comment by kmamykin** [comment]
AWS seems to have added webpack support recently
https://github.com/aws/aws-sdk-js/blob/ee4148330a38d51f7806b7e014b11c9c0be3a5c5/CHANGELOG.md#260
