### ISSUE TITLE
babel runtime error for es5 module (babel-runtime v5.* vs v6.*)

### ISSUE THREAD

**Issue by vpezeshkian** [insin/nwb#167]
`nwb build` somehow puts:
```javascript
var _interopRequire = require('babel-runtime/helpers/interop-require')['default'];
```
on the first line of the module in es5 (lib) if there is any reference to `default`.

I have `index.js` under `src` which exports modules like this:  
```javascript
export {default as MyModule} from './mymodule'
```

But babel-runtime 6.* does not have `interop-require` under `helpers`.
Please tell me how to prevent this from happening.

Thanks.

**Comment by insin** [comment]
Which version of nwb, project type and config do you have?

If I create a new `react-component` project with nwb 0.12, this `src/index.js`...

```js
export {default as MyModule} from './mymodule'
```

...gets transpiled to this in `lib/index.js`:

```js
'use strict';

exports.__esModule = true;

var _mymodule = require('./mymodule');

Object.defineProperty(exports, 'MyModule', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_mymodule).default;
  }
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

**Comment by vpezeshkian** [comment]
Yes that's right, I created new component just to test that and you are right...
But for my components it still does that. I removed es6 and lib and rebuild it again.
```javascript
  "devDependencies": {
    "nwb": "0.12.x",
    "react": "15.3.x",
    "react-dom": "15.3.x"
  },
```

This is what mine outputs
```javascript
'use strict';

var _interopRequire = require('babel-runtime/helpers/interop-require')['default'];

Object.defineProperty(exports, '__esModule', {
  value: true
});
var _myModule = require('./my-module');

exports.Workspace = _interopRequire(_myModule);
```

**Comment by vpezeshkian** [comment]
My bad, `nwb build` is using globally installed `nwb` which was on version `0.11`.
Upgraded and issue got fixed.

**Comment by insin** [comment]
I think global nwb should be changed to either warn or refuse to run if it doesn't match the required version in package.json.

**Comment by insin** [comment]
Closing this resolve issue and creating #176 for the change to nwb
