### ISSUE TITLE
Express middleware: Force reload page after failed hot reload 

### ISSUE THREAD

**Issue by tomitrescak** [insin/nwb#168]
Hi, is there any way how can I force reload page on unsuccessful HMR? 
With your tool it's all about passing --reload option, but I'm not sure how to accomplish this with your middleware. Thanks!

**Comment by insin** [comment]
Looks like I forgot to enable passing a `reload` option to the middleware.

**Comment by tomitrescak** [comment]
Good news, I'll wait for the release. Currently running webpack-middleware to handle this. The last remaining thing is to include Hot-Reload v.3 and you're gonna have a lot of happy puppies running around ;)
