### ISSUE TITLE
Is it possible to run application from different dir then src?

### ISSUE THREAD

**Issue by tomitrescak** [insin/nwb#172]
Hi, in Typescript ass I keep sources in src directory and I build to "dist" or "imports". Is it possible to configure app that it would server files from other directory then src?

**Comment by insin** [comment]
`serve` commands take an argument for the entry point to your app and `build` commands take the entry point and ouput directory - does this give you want you need?

```
nwb serve-react-app dist/index.js
nwb build-react-app dist/index.js build
```

(You *must* pass the second arg to a `build` command if your source is in `dist/`, as `dist/` is the default output directory and will be deleted prior to building!)

Check out the individual command docs here: https://github.com/insin/nwb/blob/master/docs/Commands.md#project-type-specific-commands

**Comment by insin** [comment]
Closing in favour of #115
