### ISSUE TITLE
react-flexbox-grid not loading correctly

### ISSUE THREAD

**Issue by vamsiampolu** [insin/nwb#174]
I am having a bit of trouble with react-flexbox-grid showing empty `className` values. This is my existing config:

```
var autoprefixer = require('autoprefixer')
var precss = require('precss')

module.exports = {
  type: 'react-app',
  webpack: {
    compat: {
      enzyme: true,
      'json-schema': true
    },
    loaders: {
      css: {
        modules: true,
        sourceMap: true,
        importLoaders: 1,
        localIdentName: '[hash:base64:5]'
      },
      postcss: {
        defaults: [
          precss(),
          autoprefixer()
        ],
        vendor: [
          autoprefixer({add: false})
        ]
      },
      extra: {
        module: {
          loaders: [
            {
              test: /(\.scss|\.css)$/,
              loaders: ['style-loader', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap'],
              include: /flexboxgrid/
            }

          ]
        }
      }
    }
  }
}
```

I have also installed the `nwb-sass` module as well. This is the recommended configuration suggested by the library:

```
 module: {
    loaders: [
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
      }
    ]
  }
```

How should I configure `nwb` to enable loading the plugin?

**Comment by insin** [comment]
If react-flexbox-grid is the *only* CSS you're importing from `node_modules/` you could configure the `css-loader` in the [default `vendor-css-pipeline` loader](https://github.com/insin/nwb/blob/master/docs/Configuration.md#default-loaders) like this:

```js
module.exports = {
  webpack: {
    loaders: {
      'vendor-css': {
        modules: true
      }
    }
  }
}
```

I haven't encountered dependencies asking for a specific loader setup like this before, so nwb doesn't currently provide a way to say "also create an additional style loading pipeline with *this* configuration", it just has a single loader pipeline for all CSS required from `node_modules/`.

**Comment by vamsiampolu** [comment]
Thanks, @insin, the library also has a peer dependency on babel-polyfill:

https://github.com/roylee0704/react-flexbox-grid/blob/master/package.json

I like the idea of having CSS modules switched on by default. I am currently using material-ui which means that the config will work for me now but if I were to include a module like react-bootstrap which uses global css would I have to add additional config in `extra`  for it.

**Comment by insin** [comment]
You can now configure custom nwb v0.16.0 which allows you to provide a unique rule per dependency if you need it.

See the [Stylesheets docs](https://github.com/insin/nwb/blob/master/docs/Stylesheets.md#stylesheets).
