### ISSUE TITLE
Correct way to import external libs (react-app)

### ISSUE THREAD

**Issue by vpezeshkian** [insin/nwb#180]
I don't know webpack very well, and I need to import external libraries and framewoks' css and js files into my react-app. I have created `css` and `js` folders under `src` and put necessary libs there.

importing directly into `index.html` is not working:
`<link href="/css/material/css/materialize.min.css" rel="stylesheet">` 
or 
`<script src="/js/jquery-3.1.1.min.js"></script>`

Importing into `index.js` works only for css but not js: `import './js/jquery-3.1.1.min.js'`

What is the best way to import external CSS and JS files?

**Comment by insin** [comment]
The best way is usually to install from npm and use `require()` or `import` to import from `node_modules`.

```
npm install materialize-css
```
In `index.js:`
```
import 'materialize-css/dist/css/materialize.min.css'
```

With the jQuery import do you want to expose it globally (equivalent to using a `<script>` tag) or just import it for use in a module?

---

If you have manually-managed files you want to include via `index.html`, you can put them in the `public/` directory, which will be served via the development server and copied to `dist/` when you build.

**Comment by vpezeshkian** [comment]
Yes I have customized materialized js, so I guess npm module wouldn't be option for that.
Since I'm putting js libs in `/public/js` might as well put the css there `/public/css`.

Thanks.

**Comment by SHAPPY0** [comment]
Hi, 
I am also facing the same issue. I have some custom JS files which is used for design the HTML template. and I guess these  files would not be available in npm module. 
And I put the JS files in` /public/js` even its not working.
Please help me
Thanks

**Comment by ronaiza-cardoso** [comment]
Hi, I have the same issue, when I run my lib on demo mode the css is imported, but when I publish the package the css is not exported. I'm using this lib `import 'react-table/react-table.css';`
