### ISSUE TITLE
A couple of CLI errors when creating new react-component

### ISSUE THREAD

**Issue by stowball** [insin/nwb#182]
Upon running `nwb new react-component my-component`, you get

``` sh
create tests/index-test.js
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file****
```

Everything still seems to work though.

OSX 10.11.6, node v.4.5.0

**Comment by insin** [comment]
Are there any apostrophes in the path to the new project directory?

Sounds like another place we should be passing command arguments properly instead of creating a command string which also contains arguments.

**Comment by stowball** [comment]
Nope, no apostrophes. The path was `~/Documents/Git`
