### ISSUE TITLE
Built Structure

### ISSUE THREAD

**Issue by tbillington** [insin/nwb#190]
After building I have `index.js` in `lib/` and `es/` along with the rest of the library in various sub-directories. Usually I'd do something like `import foo from 'mypackage/UI/Box'`, but with the structure from the built versions I now have to do `mypackage/lib/UI/Box`. Is there a nicer way to remove the reference to `lib/` or `es/` in the import path?

The `package.json` has

```
"main": "lib/index.js",
"jsnext:main": "es/index.js",
"module": "es/index.js",
```

**Comment by insin** [comment]
Have your `index.js` re-export all the components then you can do `import {Box} from 'myPackage'`.

Here's an example of React Bootstrap doing this: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/index.js

If the project using `myPackage` is also using nwb, you can use [`babel.cherryPick` config](https://github.com/insin/nwb/blob/next/docs/Configuration.md#cherrypick-string--arraystring) to transform those imports into individial imports.

Once Webpack 2 lands you will get this behaviour for free - it should use the build from `es/` and only bundle the components you actually use when importing this way.
