### ISSUE TITLE
Is there a difference between how nwb builds vs plain webpack build?

### ISSUE THREAD

**Issue by vpezeshkian** [insin/nwb#192]
Hi all,

I use this tool and it doesn't play well with [videojs HLS plugin](https://github.com/videojs/videojs-contrib-hls) well, the videos are not playing. But it works fine with simple webpack application.

Mainly because of `webworkify` module. There is a  [thread](https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-260689739) going on HLS side. 

It seems like the above mentioned module should be swapped out with `webworkify-webpack-dropin`, but doing so doesn't resolve my issue.

Could you please tell me if there are differences on the packaging? 

Thanks.

**Comment by insin** [comment]
nwb just creates a regular Webpack config for you.

Set a `DEBUG` env variable to `nwb` and an `NWB_TEST` env variable to `true` before starting the dev server to see what it generates.

`devtool` config should go in `webpack.extra`, but it doesn't seem to make a difference.

**Comment by insin** [comment]
Here's a potential issue - it looks like webworkify-webpack-dropin is looking for generated `__webpack_require__()` calls which use integer modules ids:

https://github.com/Ambroos/webworkify-webpack-dropin/blob/master-v1/index.js#L62

nwb generates a Webpack config which uses `NamedModulesPlugin` in dev mode (so it's easy to see what's hot-reloading) and `HashedModuleIdsPlugin` for production builds (for stable module ids), both of which will generate `__webpack_require__()` calls which use double-quoted strings.

**Comment by vpezeshkian** [comment]
Yes exactly, the `HLS` stream  is transcoded differently, ids vs string.
So is there any way to tackle this? `HLS` videos can't be played if using `nwb`?

**Comment by vpowers** [comment]
@insin I'm having the same issue as @vpezeshkian.  How could I specify environment in the nwb.config file?  Looking to see if I force it to production env, if this will resolve my issue with the webworkify-webpack-dropin.  Or is there a way to force using the HashedModuleIdsPlugin, within the webpack.config, in any environment?

**Comment by vpowers** [comment]
In case someone comes along and needs to support videojs-contrib-hls in a react app using nwb, I have forked @Ambroos webworkify-webpack-dropin to support the variance in webpack and nwb bundled code:

https://github.com/vpowers/webworkify-nwb

Follow the instructions in this [comment](https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-258400412) but use the module above instead.

You can find example usage here:
https://github.com/vpowers/simple-react-app
