### ISSUE TITLE
Inferno support?

### ISSUE THREAD

**Issue by trueadm** [insin/nwb#194]
It would be good to get native Inferno support into nwb. Is this even a possibility?

**Comment by insin** [comment]
Yes, should be doable - what does Inferno need in terms of Babel config for development serving and prod builds?

The React support is mostly just commands in `src/commands/` which set up some React-specific settings for either building or serving, and some support in `src/createBabelConfig.js`.

Inferno support should just be a case of having commands which set things up simlarly, plus support for any extra Babel config required and a skeleton for Inferno apps in `templates/`.

Things could be modularised more to allow extra project types as plugins (and implement all the existing ones plugins), but I haven't needed that or had the time to work out the fiddly bits yet, so it's currently "no abstraction is better than the wrong abstraction", with a *lot* of duplication in `src/commands/`,

**Comment by trueadm** [comment]
That sounds good. Once I get some time I can work on getting an Inferno template and setting up the config. We could also add `--inferno` a bit like `--preact` so it uses `inferno-compat` package to do the same things.

**Comment by insin** [comment]
Oh, cool, if there's a similar compat package I can add `--inferno` to the `next` branch later this evening.

**Comment by trueadm** [comment]
Yep, use `inferno-compat@beta23`, you will also need to ensure `inferno@beta23` is in there too :) thanks man!

**Comment by trueadm** [comment]
Thanks mate :)
