### ISSUE TITLE
Discussion: Rename repo

### ISSUE THREAD

**Issue by caseybaggz** [insin/nwb#199]
Not sure where `nwb` comes from but it seems like we can make a better naming convention for such a great tool as this?

maybe something like: `react-npm-bootstrap` or `create-react-npm-package` or `create-npm-package` to compliment the `create-react-app`?

**Comment by insin** [comment]
I wanted its name easy to type (so short) and meaningless 😸 

It also has partial support for Inferno and Preact (apps and compat builds) in v0.13, and will have first-class support for them equivalent to React in v0.14.

I was thinking maybe renaming to React All The Things (`ratt`) at some stage (perhaps calling that 1.0) but @threepointone just called dibs on [rat-based tooling names](https://github.com/threepointone/ratpack).

I love the idea of having a `ratt run` command.

**Comment by insin** [comment]
Closing this for now, as there are no plans to rename in the immediate future.
