### ISSUE TITLE
Allow test setup to be replaced?

### ISSUE THREAD

**Issue by bebraw** [insin/nwb#2]
I rely on Karma+Mocha+Chai+Phantom in my current test setup. Do you think it would make sense to allow the testing portion to be replaced with something else? Ideally I would push my setup to a package of its own and then feed it to nwb somehow (`.nwb`?).

**Comment by insin** [comment]
I just haven't given much thought to how each piece could be made customisable yet.

The biggest problem I foresee is resolution of custom dependencies for karma, webpack and babel which can be resolved locally and in a CI environment.

**Comment by bebraw** [comment]
> The biggest problem I foresee is resolution of custom dependencies for karma, webpack and babel both locally and in a CI environment.

I would expect it would be up to the custom testing package to deal with the karma and such bits (about 10 deps or so).

> I just haven't given much thought to how each piece could be made customisable yet - suggestions welcome.

I would need two hooks: *test* and *test-unit*. Let's say we have `nwb.config.js`, I would expect it would look something like this:

```javascript
import nwbKarmaMocha from 'nwb-karma-mocha';

// the functions are factories so you can customize them further
// they return execution instructions for nwb
export default {
  test: nwbKarmaMocha.test(),
  testUnit: nwbKarmaMocha.testUnit()
};

// obviously export default nwbKarmaMocha would work
// but I want to show the basic mapping
```

Both of these cases would need to have control over execution. I expect each hook needs to return your webpack base template so they can customize it.

I think something like this would be a starting point and it doesn't seem overly complex to me.

**Comment by insin** [comment]
This is how you can get the setup you want via `nwb.config.js` as of the next commit I'm trying to land:

```js
module.exports = {
  // ...
  karma: {
    frameworks: ['mocha', 'chai', /* other stuff from karma-chai-plugins */],
    plugins: [
      require('karma-chai-plugins')
    ]
  }
}
```

You'd just npm install `karma-chai-plugins` (or whichever plugin you're using) and have it in your own project's `devDependencies`.

**Comment by bebraw** [comment]
@insin Cool. I would love to start porting my [component boilerplate](https://github.com/survivejs/react-component-boilerplate) to use nwb once you feel it's stable enough. I think just getting the test setup to work through nwb might be a small win.

I imagine I would just push the Karma bits to a package of their own and glue nwb and that together at the boilerplate to keep it maintainable. The problem with my current solution is that even in the best case it's just a snapshot. As a result updating projects is a chore. Ideally you would just bump nwb + related packages and that's it.

**Comment by insin** [comment]
Yup, that's the driver for me too, consolidating my development tools into nwb and making my entire ESLint setup be a one-package deal too.

**Comment by bebraw** [comment]
@insin Ok, cool.

Let me know when you want me to give it a go. I'm a little busy right now (a couple of weeks) but I'll get to it as they payoff is so good. :+1:
