### ISSUE TITLE
Migrating to v0.13 causes issue

### ISSUE THREAD

**Issue by vpezeshkian** [insin/nwb#205]
First I uninstalled global nwb, then installed it locally.
when doing so `npm ls nwb` threw peer dependency error `babel-core` was missing, so it wouldn't start on `{path to nwb module}\nwb.js serve`.
Then I npm installed it as peer dependency and it starts to work.

However when Jenkins build the project, I receive the following error: 
`Error: Cannot find module '{path to project}/node_modules/babel-runtime/helpers/extends' from {path to project}/lib/wc-workspace`

Is there anything I do wrong while migrating?

Thanks.

**Comment by insin** [comment]
The `babel-core` error is a bit weird, not sure what's happening there. I would try uninstalling and reinstalling nwb from scratch first to make sure all dependencies are there.

Is there any extra configuration in your `nwb.config.js` file?

Does anything look out of place in the generated Webpack config if you set a `DEBUG=nwb` environment variable?

Does your project structure much different from what nwb's skeleton app creates? It looks like you're running `serve` from a nested directory.

A relevant change in 0.13 could be that [we now specify the path to babel-runtime when creating Babel config](https://github.com/insin/nwb/blob/7c5208fe148c3aa39536d260328870eaa545226a/src/createBabelConfig.js#L89-L110), so it would be useful to see what that gets set to using debug output.

**Comment by vpezeshkian** [comment]
One thing I noticed just now which is not good is that modules are required with absolute path with `./node_modules/nwb/lib/bin/nwb.js build` and also `./node_modules/nwb/lib/bin/nwb.js build --set-env-NODE_ENV=production`

```javascript
var _extends2 = require('/Users/{my-user-name}/projects/{my-project}/node_modules/babel-runtime/helpers/extends');

var _extends3 = _interopRequireDefault(_extends2);

var _classCallCheck2 = require('/Users/{my-user-name}/projects/{my-project}/node_modules/babel-runtime/helpers/classCallCheck');
And more...
```

Notice that I removed global `nwb` and running the command from `node_modules`, is that the correct way of running if there is no global `nwb` installed?

**Comment by vpezeshkian** [comment]
Yea, this is a bug I believe in 0.13.x. 
So I decided to try one more time with globally installed `nwb`, now the output is pointing to where global `nwb` is installed

```javascript
var _extends2 = require('/usr/local/lib/node_modules/nwb/node_modules/babel-runtime/helpers/extends');
var _extends3 = _interopRequireDefault(_extends2);
var _classCallCheck2 = require('/usr/local/lib/node_modules/nwb/node_modules/babel-runtime/helpers/classCallCheck');
And more...
```

**Comment by insin** [comment]
Which type of project is this? Can you provide your nwb.config.js?

**Comment by insin** [comment]
Does v0.13.6 fix this?

https://github.com/insin/nwb/releases/tag/v0.13.6

**Comment by vpezeshkian** [comment]
Yoohoo, yes, this new release v0.13.6 seems to fix the issue. but fyi I'm pasting my nwb config, this project is a react component which I inject in other projects as dependency...

```javascript
module.exports = {
  type: 'react-component',
  babel: {
    stage: 0,
    runtime: true
  },
  npm: {
    esModules: true,
    jsNext: true,
    global: '',
    externals: {
      'react': 'React'
    },
    umd: false
  },
  webpack: {
    aliases: {
      'webworkify': 'webworkify-nwb'
    },
    extra: {
      devtool: 'source-map'
    },
    html: {
      favicon: 'vendors/favicon.ico'
    }
  }
}
```

**Comment by insin** [comment]
Closing as fixed.
