### ISSUE TITLE
Use Classes in the React Template

### ISSUE THREAD

**Issue by ntwcklng** [insin/nwb#216]
To match the Preact & Inferno Template, we should use `Class x extends React.Component` for creating a React Component instead of `React.createClass({})`.
In the near future `React.createClass({})` will be replaced with `Class x extends React.Component`. See https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html

**Comment by insin** [comment]
I think we should do this when/if we drop the react-transform Babel plugin in favour of the latest React Hot Loader, which AFAIK supports patching methods defined as class properties for binding.
