### ISSUE TITLE
Use babel-preset-latest

### ISSUE THREAD

**Issue by feimosi** [insin/nwb#229]
This issue is a: 

- [ ] Bug report
- [X] Feature request
- [ ] Question / support request
- [ ] Other

Babel offers a nice preset that's always corresponding the current JavaScript standard:
https://babeljs.io/docs/plugins/preset-latest/

I can make a PR if you approve the request.

**Comment by insin** [comment]
What's the benefit of moving to this preset? The features in the `es2017` preset are already included in the `stage-3` preset and won't be removed from `stage-3` until Babel 7 (https://github.com/babel/babel/issues/5117).

Looking at that issue I can see some other changes which are required to nwb's current Babel config:

- [ ] should only be using the `es2016` preset if use of a `stage-x` preset is disabled by user configuration, as the exponentiation operator transform is currently being duplicated.
- [ ] should also use the `es2017` preset if use of a `stage-x` preset is disabled by user config, as `stage-3` currently contains everything in `es2017`

**Comment by feimosi** [comment]
The benefit is that every year you get the correct features enabled without any need to modify Babel's config. And I don't think duplication of plugins is an issue for Babel, correct me if I'm wrong.

**Comment by insin** [comment]
I've asked if duplicated plugins can cause problems in the linked issue.

If it's not an issue then I agree it would be easier to just manage one preset instead of multiple `es2XXX` presets.

**Comment by insin** [comment]
nwb is now using babel-preset-env, which babel-preset-latest was deprecated in favour of
