### ISSUE TITLE
Support use of babel-preset-env?

### ISSUE THREAD

**Issue by insin** [insin/nwb#231]
Suggestion: support use of  `babel.env` config which, when provided, uses `babel-preset-env` in generated Babel config instead of the `es201x` presets.

What are the benefits vs. cons and gotchas?

**Comment by wmertens** [comment]
It will make server side code maybe a little faster, and slightly easier to debug.

**Comment by insin** [comment]
Looks like using `babel-preset-env` will cause issues creating minified builds if you configure it for modern browsers, as UglifyJS doesn't currently support ES6.  You'd need to use its harmony branch, as documented here: https://github.com/webpack-contrib/uglifyjs-webpack-plugin

**Comment by insin** [comment]
nwb is now using babel-preset-env, as babel-preset-es20XX is deprecated
