### ISSUE TITLE
Specifying that files shouldn't be counted in code coverage

### ISSUE THREAD

**Issue by joshwcomeau** [insin/nwb#235]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

------

Hi!

I'm using NWB to develop a suite of React components, and everything's going great. I've been testing as I write, and was dismayed to see that I only had ~50% code coverage, despite doing TDD:

<img width="570" alt="screen shot 2017-01-17 at 9 02 32 am" src="https://cloud.githubusercontent.com/assets/6692932/22023321/bd23590e-dc93-11e6-8ae2-fbd31c9330c8.png">

Looking at the generated report, it turns out that I actually have very good coverage, except a single file: `polyfills.js`.

I found [the instructions for excluding files from coverage reports by treating them as test files](https://github.com/insin/nwb/blob/master/docs/Testing.md#excluding-test-directories-from-coverage), but then the tests fail, because it ignores the module entirely:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "../../polyfills"
  at webpack:///src/components/Every/Every.js?15a9:3:0 <- src/components/Every/Every.test.js:72807
```

Looking at the docs for [karma-coverage](https://github.com/karma-runner/karma-coverage#basic), it seems like I need to update 'preprocessors' to have a glob that excludes this file... but I'm not sure how to "reach in" and do that with NWB.

Appreciate any insight you can shed! And it's not an urgent priority for me if excluding files from coverage isn't supported :)

**Comment by insin** [comment]
nwb uses [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) for instrumentation - being able to manually specify files in your own project to exclude from coverage just isn't a use case I'd accounted for, so I'd need to make that configurable.

**Comment by insin** [comment]
On second thoughts, `karma.testDirs` config should be usable for what you want to do, having just looked at how it's used. It's named as if it must specify directories, but it doesn't have to - if provided, this config is only ever used to configure babel-plugin-istanbul's `exclude` option.

Try this in `nwb.config.js`, substituting the correct path:

```js
karma: {
  testDirs: ['src/path/to/polyfills.js']
}
```

**Comment by joshwcomeau** [comment]
Hi @insin,

Thanks for the quick reply :)

So yeah, `polyfills.js` is for ES5/ES6 array methods like `find`, `every`, `isArray`. After opening this issue I realized that indeed I should probably make it its own dependency; that way developers can choose whether to include it or not, if they're only targeting modern browsers.

It winds up being really tiny (<1kb gzipped), but I like the idea of my library being as lean as possible, so I'll likely do that :)

Thanks for the tip about `testDirs`. I saw it, but assumed it worked the same as `testFiles`. I'll give it a try tonight, and report back on whether it worked or not, for anyone else who runs into a similar issue.

**Comment by joshwcomeau** [comment]
This did indeed solve my problem with no unintended side effects :D

<img width="564" alt="screen shot 2017-01-17 at 8 32 19 pm" src="https://cloud.githubusercontent.com/assets/6692932/22047286/152d6c9c-dcf4-11e6-98e8-8275c2ea6454.png">

Thanks for your quick response (and for working on a solution so quickly! I like `karma. excludeFromCoverage`).

Closing, because I no longer need support :)
