### ISSUE TITLE
Fallback routing doesn't work if contains .html

### ISSUE THREAD

**Issue by codeinabox** [insin/nwb#237]
This issue is a: 

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

I noticed that the fallback routing doesn't work if it contains .html. For example localhost/callback works fine but localhost/callback.html doesn't.

**Comment by insin** [comment]
That's [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback)'s dot rule, which is on by default. This could be disabled or made configurable if needs be.

**Comment by insin** [comment]
Closing this in favour of #304 which has details on how it will be fixed in v0.17
