### ISSUE TITLE
css loading issue?

### ISSUE THREAD

**Issue by vpezeshkian** [insin/nwb#249]
After upgrading from `nwb V0.14.x` to `nwb V0.15.x` my react app throws blob error:

/***/ }},{moduleId: "./node_modules/css-loader/index.js?{"importLoaders":1}!./node_modules/postcss-loader/index.js??postcss!./src/components/Main/main.css", module: function (module, exports, __webpack_require__) {

![screen shot 2017-01-26 at 10 44 55 am](https://cloud.githubusercontent.com/assets/6642294/22345330/9a1c790e-e3b4-11e6-93fb-0437cd5183d2.png)

My nwb config file does not have anything related to css that needed to be changed according to changelog: 
```javascript
module.exports = {
  type: 'react-app',
  babel: {
    stage: 1
  },
  webpack: {
    aliases: {
      'webworkify': 'webworkify-nwb'
    },
    extra: {
      devtool: 'source-map'
    }
  }
}
```

**Comment by insin** [comment]
Sorry, I've no idea what's going on there - I'm assuming this is related to something webworkify does?

**Comment by vpezeshkian** [comment]
I removed that alias and was still getting the blob error. 
I removed `import './main.css'` from component.js and it started to work...

**Comment by insin** [comment]
If you're using webworkify somewhere, it will still do what it's doing without the alias.

It looks like it assumes module names won't have double quotes in them, as that's why the error output you posted is invalid:

```
moduleId: "./node_modules/css-loader/index.js?{"
```
