### ISSUE TITLE
How to disable filename hashing in build

### ISSUE THREAD

**Issue by kylesheely** [insin/nwb#252]
Is there a way to disable the built-in hashing of filenames?  I have a use-case that requires it.  I've tried putting "options: { name: '[name].[ext]'}" in loader rules in my nwb.config.js but haven't found a config that works.

Thanks

This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x ] Question / support request
- [ ] Other

**Comment by insin** [comment]
Is this just for static files which are being imported to be handled by Webpack?

This should configure all the default url-loaders appropriately ([using the rule ids from here](https://github.com/insin/nwb/blob/master/docs/Configuration.md#default-rules)):

```js
module.exports = {
  webpack: {
    rules: {
      graphics: {name: '[name].[ext]'},
      svg: {name: '[name].[ext]'},
      jpeg: {name: '[name].[ext]'},
      fonts: {name: '[name].[ext]'},
      video: {name: '[name].[ext]'},
      audio: {name: '[name].[ext]'}
    }
  }
}
```

I could also add additional config to allow you  to configure the default url loader settings, which would take care of all of these in one go.

**Comment by kylesheely** [comment]
Thanks. This helps. Any way to do the same for js and css?

**Comment by insin** [comment]
[`extractText`](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extracttext-object) and [`extra`](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extra-object) should get you the rest of the way.

```js
module.exports = {
  webpack: {
    extractText: {
      filename: '[name].css'
    },
    extra: {
      output: {
        filename: '[name].js',
        chunkFilename: '[name].js'
      }
    }
  }
}
```

**Comment by kylesheely** [comment]
Much appreciated!

**Comment by insin** [comment]
What's the use-case for needing un-hashed filenames, if you can tell me? This is potentially something which could be controlled via higher-level convenience config if it would be generally useful, e.g.

```js
module.exports = {
  webpack: {
    hashFilenames: false
  }
}
```

**Comment by kylesheely** [comment]
My built assets are tracked in a separate cvs-like source control system and it would be painful to manage them with changing filenames. I suspect it's a fairly unique use-case.

**Comment by chrisfromredfin** [comment]
Just leaving an update that this has become `extractCSS`
