### ISSUE TITLE
Running tests results in 'module not found' error

### ISSUE THREAD

**Issue by TimonVS** [insin/nwb#255]
This issue is a: 

- [x] Bug report

Which versions of Node.js, npm and nwb are you using (if using it globally)?

v7.4.0

---

I'm getting a weird error when I try to run the tests with `nwb test-react`.

```
Failed to compile with 1 error.

 ERROR  in multi ./~/nwb/polyfills.js ./~/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js ./test
Module not found: Error: Can't resolve '/Users/timon/Projects/my-app/test' in '/Users/timon/Projects/my-app'
 @ multi ./~/nwb/polyfills.js ./~/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js ./test
```

`nwb test-react --server` seems to work fine though. I created a brand new project to verify the issue.

**Comment by TimonVS** [comment]
Ugh, I was really tired yesterday so I made a stupid mistake (I ran `npm start test` instead of `npm run test`).

**Comment by insin** [comment]
Amazing timing, I literally just ran `nwb new` to create a repo to try to repro this 😹

**Comment by insin** [comment]
It might be worth adding a check that the first argument to `nwb serve-*` commands is resolvable and having an explicit failure if not.

e.g. if you do `cp -R src/ test/` in a fresh React app, `npm start test` would work, as `test/index.js` will be resolved.
