### ISSUE TITLE
Use confippet for configuration

### ISSUE THREAD

**Issue by wmertens** [insin/nwb#261]
This issue is a: 

- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [x] Other

First off, I'm not currently a user of nwb :) I'm interested in it because I am developing something similar and I don't like re-inventing wheels.

Wallmart made electrode.io and it has many interesting aspects, including https://github.com/electrode-io/electrode-confippet, which builds on the conceps of node-config to make static configuration of many environments easy.

The biggest improvement it brings to the table is [templating](https://github.com/electrode-io/electrode-confippet/blob/master/templates.md). This means that you can define relative paths in the configuration, but then when webpack reads them, they are converted to absolute paths. (note that this probably doesn't work for windows right now, I suppose there should be an extra processing step to convert `/` to `\`)

**Comment by insin** [comment]
Do you have an example use in mind?

Looking at its docs, I'm not sure what the use case for confippet within nwb would be - most of the the build config (to provide working baseline config for each command) nwb uses internally and the user config it supports (other than the escape hatches for merging/tweaking webpack config) map directly to specific pieces of configuration generation code which have made toggleable or configurable.

**Comment by wmertens** [comment]
Well, in my project I use it to configure build targets, aliases, plugins,
loaders, dll list, … as well as application configuration, all in a way
that is easy to override by environment.

**Comment by insin** [comment]
Closing this as there are no plans to use it in nwb for now - it looks more like something I'd use in my own Node.js stuff so thanks for pointing it out.
