### ISSUE TITLE
Good old inline mode without HMR

### ISSUE THREAD

**Issue by bsideup** [insin/nwb#263]
Hi! 

This issue is a Feature request

I don't really like HMR because it fails with our app. Is it possible to use good old Webpack Dev Server + inline mode and disable HMR completely?

Thanks

**Comment by insin** [comment]
Yes, this is something it would be easy to flag off in the appropriate `serve` command.

**Comment by ochervak** [comment]
Is there any updates ? Have troubles with HMR in my app too. Is there any workaround i can apply right now ?

**Comment by KatSick** [comment]
@insin how to use `--no-hmre` with `app.use(require('nwb/express')(express, { reload: true }));` ?

**Comment by KatSick** [comment]
@insin i fix it with `app.use(require('nwb/express')(express, { hmre: true, hmr: true, reload: true  }));
` since i see in source code `hmre: !options.hmr || !options.hmre,` in `expressMiddleware`.

**Comment by insin** [comment]
Yeah, that's buggy -the next release should be coming soon, a fix for that logic will be included in it.
