### ISSUE TITLE
css loader fails

### ISSUE THREAD

**Issue by pedrocostadev** [insin/nwb#266]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [ X] Question / support request
- [ ] Other

Hi,

I am trying to create a react component and load css files of components when run 'npm run build' but there is no css files in 'es' or 'lib' folder despite the JavaScript file have a reference to them.

My component import:

          import './TripleSelectBox.css';

My config file rules options (after many different tries):

     webpack: {
         rules: {
           babel: {
               test: /\.jsx?/
           },
	  'css-loader': {
                test: /\.css$/,
          }
       },

I am working with last release of nwb.
Can anyone point me to a working example?

**Comment by insin** [comment]
Are you passing a `--copy-files` flag when running the [build](https://github.com/insin/nwb/blob/master/docs/Commands.md#nwb-build) command?

> If you have non-JavaScript files in src/ which you want to be copied over when building, such as CSS files, pass a --copy-files flag.

The `webpack` section of the config file is only used when creating a UMD build - the part of the build which creates the es/ and lib/ build is just using Babel's CLI.

**Comment by pedrocostadev** [comment]
Ok, my bad... I forget that. Thanks
