### ISSUE TITLE
Import jquery with bootstrap

### ISSUE THREAD

**Issue by pedrocostadev** [insin/nwb#267]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x ] Question / support request
- [ ] Other

Hi can anyone tell me how import jquery with bootstrap? I'm doing this:

    import 'jquery/dist/jquery.js';
    global.jQuery = require('jquery');

    import 'bootstrap/dist/css/bootstrap.css';
    import 'bootstrap/dist/js/bootstrap.js';

I'm already  put jquery in externals in many ways like this:

    "jquery": "jQuery",

But, nothing works. It keeps me giving this error:  "Bootstrap's JavaScript requires jQuery".
What i am doing wrong?

Thanks

**Comment by LeoDT** [comment]
maybe https://webpack.js.org/plugins/provide-plugin/ could help.

**Comment by insin** [comment]
Looks like `ProvidePlugin` is the way to go.

**Comment by LukeIvie** [comment]
@insin I'm a bit new to all of this, how would I go about using ProvidePlugin with NWB to get this set up? I'm having the same problem currently...

**Comment by insin** [comment]
@LukeIvie here's an example project: https://github.com/insin/nwb-examples/tree/master/bootstrap-web-app

**Comment by LukeIvie** [comment]
@insin thank you so much! That's perfect.
