### ISSUE TITLE
Working UMD example

### ISSUE THREAD

**Issue by coryhouse** [insin/nwb#282]
This issue is a: Question

Is there a working example of a UMD build running in JSFiddle/Codepen/JSBin deployed somewhere? I'm having issues getting the UMD build to work on one of the above services, and would like to compare to a working example.

Really impressed with nwb! Great work! 👍

**Comment by insin** [comment]
@coryhouse Sure, here's the [react-auto-form](https://github.com/insin/react-auto-form) demo using the UMD build in a Codepen:

https://codepen.io/jbscript/pen/qmzgoX
