### ISSUE TITLE
Feature request: disable CommonJS / ES5 / lib build

### ISSUE THREAD

**Issue by treshugart** [insin/nwb#285]
Currently we only have a use case for using the UMD build. We want to disable building `lib` for a few reasons:

- It speeds up our builds by a wide margin (70+ components in a Lerna mono-repo)
- We currently use loaders, which makes exposing `es` / `lib` a problem for consumers because they must know about the implementation details.
- We point `main` to the `umd` bundles to get around ^, there fore we don't want to incur the overhead of `es` / `lib` at the moment.
- We do want to get rid of `umd` in the future and only use `es` / `lib` but that requires a lot of work to get rid of the loaders.

What I am proposing, in the form of a PR, is:

- Allow an `npm.cjs` option to be specified as `false` to switch off the CommonJS build

This means that even though it's a new feature, it's not a breaking change as the `lib` build will still be generated by default (opt-out).

**Comment by treshugart** [comment]
Implemented in fork while awaiting PR: https://www.npmjs.com/package/@treshugart/nwb.

**Comment by treshugart** [comment]
Closing because PR was merged. Thank you!

**Comment by insin** [comment]
Thanks for the PRs, aiming to cut a release of whatever's in master on Thursday morning (AEST)
