### ISSUE TITLE
Exit code 0 when the build fail?

### ISSUE THREAD

**Issue by alex-pex** [insin/nwb#290]
This issue is a:
- [X] Bug report
- [ ] Feature request
- [X] Question / support request
- [ ] Other

Hello,

I ran a strange issue with nwb on my production environment. I configured eslint-loader to be run with the build, but eslint-loader was a devDependency and was expected to fail on production.

On NODE_ENV=production, I ran ```npm run build``` and it failed with the message : "Module not found: Error: Can't resolve 'eslint-loader'". The problem is: the exit code is still 0 and my Travis tests didn't fail.

The latest version changelog says "Explicitly call process.exit(0) from the nwb command when there are no errors running a command [#262]", maybe it is related to this ?

```
node -v
v6.10.0

npm -v
3.10.10

nwb -v
v0.15.6
```

**Comment by insin** [comment]
Is there a repo I could use to repro this?

**Comment by alex-pex** [comment]
I don't have a repo to share, but here is what I do : 

in index.js:
```js
import renderApp from 'umbra/render';
import 'umbra/styles/material-theme.scss';
import 'umbra/styles/bootstrap-theme-vendor.scss';
import 'umbra/styles/bootstrap-theme-core.scss';
import 'aaa';

// eslint-disable-next-line no-restricted-properties
renderApp(document.getElementById('root'));
```

Then : ```npm run build && echo "it's alright"``` and I get : 
```
√ Cleaning app
× Building React app

Failed to compile with 1 error.

 ERROR  in ./src/index.js
Module not found: Error: Cannot resolve module 'aaa' in (...)
 @ ./src/index.js 13:0-14
it's alright
```

**Comment by insin** [comment]
Thanks, looks like need to explicitly check for build errors after running a build instead of relying on Webpack calling back with an error (which must be reserved for genuine build failures, not completion with build errors).
