### ISSUE TITLE
Allow to pass useable styles option to style loader

### ISSUE THREAD

**Issue by kirill-konshin** [insin/nwb#294]
This issue is a: Feature request.

- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [ ] Other

https://github.com/webpack-contrib/style-loader#reference-counted-api

Currently this option is not supported by NWB.

**Comment by kirill-konshin** [comment]
Bump

**Comment by loklaan** [comment]
Hello!

You should be able to [override the default webpack rules](https://github.com/insin/nwb/blob/master/docs/Configuration.md#rules-object) for style loaders (`css-pipeline` & `vendor-css-pipeline `) in `nwb.config.js`.

For reference, [here is the code](https://github.com/insin/nwb/blob/master/src/createWebpackConfig.js#L145) for where the default rules for css are being configured.

Ref counts are likely too niche a case to add as a high level option in the nwb config, sorry, but it's great that you've brought it up for posterity.

Let me know how it goes! In the meantime, I'll close the issue.

**Comment by kirill-konshin** [comment]
First of all, I've found a bug #300 Custom CSS rules are not applied on SASS/LESS rules.

But the saddest part for my case is that useable styles are enabled by using different loader: `style-loader/useable`, it's not an option parameter...

So when I set `{style: {loader: require.resolve('css-loader/useable'}}` I get:

```
[ { loader: '/boilerplate/node_modules/style-loader/index.js',
    options: 
     { loader: '/boilerplate/node_modules/style-loader/useable.js' } },
```

I agree that it is a niche use case, but it's very useable if you need to swap skins in real time, so you remove one style tag and add another one.

P.S. There is an unpredicted behavior, the following two configs produce same results: 

```
css: {options: {modules: true}}
css: {modules: true}
```

Should I create a separate bug for that too?

**Comment by kirill-konshin** [comment]
If you're OK then I can pass a new flag for that. Should be a very simple change...

**Comment by loklaan** [comment]
Sorry that you're frustrated, but this should be configurable. We won't be added new flags for `nwb-config.js` for this case.

**Comment by loklaan** [comment]
I've replied to #300 - hopefully it'll help with overall understanding of how to override existing parts in the rules pipelines.

**Comment by kirill-konshin** [comment]
What do you mean by saying "this should be configurable" together with "won't be added new flags"? In simple CLI mode there's no access to resulting Webpack config which I could post-process...

Regarding #300 — got it, thanks.

**Comment by loklaan** [comment]
I looked like you were suggesting adding a custom flag to use `css-loader/useable` over `css-loader`.

**Comment by kirill-konshin** [comment]
Yes, I was hoping that we can add something like `module` option for `style` pipeline. Something like `useable: true` would fit.

**Comment by loklaan** [comment]
`modules` is a loader option for the css-loader. This is how options work in the `nwb-config.js` - they get treated as options for the loader.

There is no option for style-loader; you simply replace it with a different loader.

Replacing the `loader` prop in `webpack.rules.style` with `style-loader/useable` _should_ have replaced the default `style-loader`... If that isn't the case, would you mind opening another issue for it? (this is 100% how we should be configuring your case)

**Comment by kirill-konshin** [comment]
I see, OK, option is not 100% semantic for the case. Setting the loader should be a better way.

Something like this:

```js
{
  style: {
    loader: require.resolve('css-loader/useable',
    options: {module: true}
  }
}
```

But as I mentioned earlier, everything from `style` and `style.options` goes as `options`.

**Comment by loklaan** [comment]
That's unexpected - `loader` should be overridable. Could you make another issue for that? We can track progress in there rather than here.

**Comment by kirill-konshin** [comment]
Created #303.
