### ISSUE TITLE
Respect NODE_PATH environment variable

### ISSUE THREAD

**Issue by cguedes** [insin/nwb#295]
This issue is a: 

- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [ ] Other

Is there a plan to support NODE_ATH environment variable. This support was added to create-react-app in [0.4.0 / sept 2016](https://github.com/facebookincubator/create-react-app/blob/master/CHANGELOG.md#040-september-2-2016).

This allows lib/app authors to build the app using something like:

`NODE_PATH=./src nwb build-react-component`

And write this (components is a folder inside /src): 

```js
import { GeneralSettings, CustomHeadersSettings } from 'components/settings'
```

instead of using `./../../components/settings`.

**Comment by loklaan** [comment]
Hey thanks for making the issue.

This is already supported, but not implicitly. You've got to set the following in the config:

```js
module.exports = {
  webpack: {
    extra: {
      resolve: { root: "./src" }
    }
  }
}
```

I personally use [aliases](https://github.com/insin/nwb/blob/master/docs/Configuration.md#aliases-object) for my projects. You may want to look into it.

**Comment by cguedes** [comment]
@loklaan Thanks for your feedback. I missed that part in the documentation.
