### ISSUE TITLE
Any plan to add typescript support?

### ISSUE THREAD

**Issue by LeoDT** [insin/nwb#299]
- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [ ] Other

Any plan to add typescript support? just curious.

**Comment by loklaan** [comment]
Hello!

Typescript is great, but not everyone uses it. It likely won't be added as a high level option in nwb for some time, unless @insin falls for it ❤️ 😉 .

For now, you should be able to [add the typescript loader](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extra-object) to `nwb.config.js` to achieve integration in a project.

Let me know how it goes. I'll close the issue for now.

**Comment by Gregor1971** [comment]
For anyone looking... 

I tried this and found [this config](https://gist.github.com/Gregor1971/8d8f37ae117bec133e67e05733fdea73#file-typescript-nwb-config-js) to work for me.

Added dependencies, added [tsconfig.json](https://gist.github.com/Gregor1971/3e9a7464c2e41dd559b0465127dcbd68) and [tslint.json](https://gist.github.com/Gregor1971/44c0473e04b7b51500fdcb6a763b5225) and converted the index.js files in src and demo/src to .tsx

**nwb build** and **serve** both work, but serve lost its hot-reload.  It does watch and re-transpile, but needs a page refresh.

**Comment by drager** [comment]
@Gregor1971: How do you do for `build-react-component`?

**Comment by Gregor1971** [comment]
I didn't get that deep with typescript and nwb.  I ended up building up an odd boilerplate with react-native-web and chose to go with flow for now.

**Comment by tnrich** [comment]
I'd like a top level, out of the box, typescript support option. :)
