### ISSUE TITLE
Unable to install nwb globally gets errror 

### ISSUE THREAD

**Issue by kamarajuPrathi** [insin/nwb#305]
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/XXXX/.nvm/versions/node/v6.9.0/bin/node" "/Users/kprat1/.nvm/versions/node/v6.9.0/bin/npm" "install" "-g" "nwb"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not found : @insin/extract-text-webpack-plugin
npm ERR! 404 
npm ERR! 404  '@insin/extract-text-webpack-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nwb'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by kamarajuPrathi** [comment]
@insin Can you check this ?

**Comment by jongold** [comment]
I'm getting the same error

**Comment by loklaan** [comment]
I've tried to replicate, but no bingo - no error.

That package is definitely on the public npm registry... are you using a registry mirror / proxy?

Does `npm info @insin/extract-text-webpack-plugin` give you a 404 as well?

**Comment by kamarajuPrathi** [comment]
@loklaan below is the error i get when doing info

**Comment by kamarajuPrathi** [comment]
C02LQEB1FD57:~ kprat1$ npm info @insin/extract-text-webpack-plugin
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/kprat1/.nvm/versions/node/v6.9.0/bin/node" "/Users/kprat1/.nvm/versions/node/v6.9.0/bin/npm" "info" "@insin/extract-text-webpack-plugin"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not found : @insin/extract-text-webpack-plugin
npm ERR! 404 
npm ERR! 404  '@insin/extract-text-webpack-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kprat1/npm-debug.log

**Comment by loklaan** [comment]
@kamarajuPrathi From the paste, it doesn't look like you typed `@insin/extract-text-webpack-plugin`.

Also honestly, I'm not sure how much I can help with this - it is almost definitely a problem with your environment. I'd suggest just trying a bunch of different things. I'll close this later issue today.

**Comment by kamarajuPrathi** [comment]
Never mind I could install I had my company npm.. made it public it worked , but failed during creation of react app . Will close this
