### ISSUE TITLE
How to access static assets from demo index.html

### ISSUE THREAD

**Issue by feelic** [insin/nwb#307]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

(using nwb v0.15.8)

Hello,
I'm new with nwb and, first off, great job, it's a great experience creating packages !

I'm trying to make a sandbox for a library of react components. My components will use css and js files that are in other packages, and that I will load with <script> tags in production.

I'm trying to replicate this behaviour in the demo sandbox with nwb. 

I have seen that it is possible to use a custom index.html for the demo by adding this to nwb.config.js
```
...
  webpack: {
    html: {
      template: 'demo/src/index.html'
    }
  }
...
```
This works perfectly.

Now I've seen in the docs that I can use static assets with a `public` directory. I created one `demo`. now my `demo` folder looks like this
```
demo/
    public/
        my-static-script.js
    src/
        index.html
        index.js
```

I'm trying to load `my-static-script` in the sandbox with a script tag like this
```
<script src="my-static-script.js"></script>
<script src="public/my-static-script.js"></script>
<script src="demo/public/my-static-script.js"></script>
<script src="demo/my-static-script.js"></script>
```
None of these work (and I've tried a few more after looking at the command files in nwb). 

I'm at a loss, have I missed something in the docs ? Can you help me please ?

**Comment by insin** [comment]
nwb uses https://github.com/kevlened/copy-webpack-plugin to copy the contents of `public/` over, which adds the files which would be copied during a build to Webpack's in-memory filesystem, which is what's being served by by webpack-dev-middleware when you run the dev server.

As such, anything in `public/` should be available under `/` when running the dev server, so try `/my-static-script.js`.

**Comment by feelic** [comment]
this does not sem to work over here 

my html file looks like this:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="/my-static-script.js"></script>
  </head>
  <body>
    <div id="demo"></div>
  </body>
</html>
```
Does the copy of `public/` happen the same way for components and apps created with nwb ?

Is there anything specific to add to `nwb.config.js` to enable it ?

Where should `public/` be located:
* `/public/`,
* `/demo/public/`,
* or `/demo/src/public/` ?

**Comment by feelic** [comment]
The public folder is copied in `demo/dist/` in [build-demo.js](https://github.com/insin/nwb/blob/master/src/commands/build-demo.js)

but it does not seem to do it in [serve-react-demo](https://github.com/insin/nwb/blob/master/src/commands/serve-react-demo.js)

maybe I missed something

**Comment by insin** [comment]
I've just spotted that we're not creating the `CopyPlugin` config for serving the demo, only when building it.

I can add this to the `next` branch, which will be almost ready for release when I finish updating outdated dependencies.

**Comment by feelic** [comment]
great, thanks :) !
