### ISSUE TITLE
new preact-cli register preact binary

### ISSUE THREAD

**Issue by quentin-sommer** [insin/nwb#308]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [ ] Question / support request
- [x] Other

Hi, the new official [preact-cli](https://github.com/developit/preact-cli) project released last week register a `preact` command. While trying it out it collided with `nwb`'s `preact` command, I had to globally remove `nwb`  to use `preact-cli`.

What could we do about it? rename the command on `nwb` side? It feels natural that `preact` claims the `preact` command name

**Comment by insin** [comment]
I agree that preact-cli should own the global `preact` command.

How about `nwb preact [run|build]`?

**Comment by quentin-sommer** [comment]
Sounds good, this way people know right away they're using `nwb` and might discover others command (react, inferno eg) by running `nwb`, thing that we wouldn't have with `nwb-preact`
