### ISSUE TITLE
--copy-files flag does not work if esModules and cjs is disabled

### ISSUE THREAD

**Issue by lukebatchelor** [insin/nwb#309]
This issue is a:

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

We have a build where esModules and cjs are disabled (we only use the umd). We want to copy some vendor files across after the build has run and would expect to be able to do this with the --copy-files flag. 

It doesnt seem to get called because we never run the `runBabel` [here](https://github.com/insin/nwb/blob/9872198bc723ba3a28e383c44c9e8a4ed8c16930/src/moduleBuild.js). 

Not sure if this is important or not, we could either implement this using the webpack copy plugin, or just add a note to the docs that the --copy-files flag is only supported in the babel builds.

Obviously we can work around it pretty easily, so not a blocker for us

**Comment by insin** [comment]
Happy to let copying files yourself as part of your build process be the solution here, as `--copy-files` is a terrible hack for the unsolved problem of distributing stylesheets.
