### ISSUE TITLE
PostCSS error in version 0.15.8

### ISSUE THREAD

**Issue by kirill-konshin** [insin/nwb#311]
This issue is a: Bug Report

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

Got the following error for any given `css` file after upgrade to 0.15.8 from 0.15.6:

```
Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/Users/xxx/node_modules/postcss/lib/processor.js:136:12)
    at new Processor (/Users/xxx/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/Users/xxx/node_modules/postcss/lib/postcss.js:73:10)
    at /Users/xxx/node_modules/postcss-loader/index.js:122:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by insin** [comment]
I also hit this while working on v0.15.8, but the Webpack version bump in the release fixed it for me.

Have you tried a re-install of your node_modules if you're using npm3? Non-determinism!

**Comment by kirill-konshin** [comment]
Yes, I did removed node_modules and made complete reinstall.

**Comment by kirill-konshin** [comment]
I am using NPM version `4.3.0`. Webpack version is `2.6.1`. I have also upgraded `nwb-sass` to `0.8.0` but the issue persists.

**Comment by insin** [comment]
Do you have a repo I can use to reproduce this locally?

**Comment by kirill-konshin** [comment]
After long debug I have figured that the issue occurs because of CSS import from SCSS file:

```scss
@import "~react-datetime/css/react-datetime.css";

.rdt {
    // stuff
}
```

**Comment by insin** [comment]
Every loader involved in handling styles had a major version bump since 0.15.x so I'll trawl the changelogs and issues to see if anything sticks out.

**Comment by evilebottnawi** [comment]
Related to https://github.com/postcss/postcss-loader/pull/234#issuecomment-305027605

**Comment by tnrich** [comment]
I'm also hitting this issue with the latest nwb v0.16.3
Thanks for the hard work @insin :)

**Comment by insin** [comment]
Thanks for the investigation @evilebottnawi

**Comment by tnrich** [comment]
@insin any update on this? It got fixed momentarily but I am hitting it again!

**Comment by insin** [comment]
Does anyone have a sample repo I can use to reproduce this?

**Comment by tnrich** [comment]
I think a simple one would be the base nwb setup for a react component plus `yarn install @blueprint/core` and then in the demo/index.js file have a require of `@import url(~@blueprintjs/core/dist/blueprint.css);`

**Comment by insin** [comment]
According to https://github.com/postcss/postcss-loader/issues/258, `ident` is needed again for postcss config to work.

nwb no longer adds this as I thought recent versions of Webpack automatically handled passing options properly, but I guess not, as `@import url(~@blueprintjs/core/dist/blueprint.css);` works once I add an `ident` to postcss-loader's options.

**Comment by tnrich** [comment]
Thank you!!

**Comment by insin** [comment]
Fix released in:
- v0.17.3 (default version) - Webpack 2, works in npm2 if you're stuck on it
- v0.18.4 (`nwb@next`) - Webpack 3, updated dependencies, new features, doesn't work in npm2 yet due to Webpack plugin `peerDependencies`)
