### ISSUE TITLE
NPM build doesn't include non .js files

### ISSUE THREAD

**Issue by cnolimit** [insin/nwb#317]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

```
node -v : 8.0.0
npm -v 5.0.0
```

Each time i create a build, the `/es` and `/lib` folders both fail to include any files which don't have a `.js` extension.
I don't no if i'm missing something, but i've read the docs and still can't seem to understand the behaviour and whether it is intended.

Is there a way to include the `.svg` and `.json` files i have in seperate folders, over to the `/es` and `/lib` folders

This is my setup
```
src/
   assets/
      *only .svg files*
   components/
      *only .js files inside*
   utilities/
      *only .js files inside*
   lib/
      *only .json files*
   index.js
```

This is what ends up in the `es/` and `/lib` folders
```
src/
   components/
      *only .js files inside*
   utilities/
      *only .js files inside*
   index.js
```

**Comment by insin** [comment]
Pass a `--copy-file` flag in your build script:

> If you have non-JavaScript files in `src/` which you want to be copied over when building, such as CSS files, pass a `--copy-files` flag.

Need to move that somewhere more prominent than the last paragraph here: https://github.com/insin/nwb/blob/master/docs/Commands.md#nwb-build

**Comment by cnolimit** [comment]
That worked Great! thanks for the help  @insin 👍
