### ISSUE TITLE
Unexpected token < (probably related to script in index.html)

### ISSUE THREAD

**Issue by IljaDaderko** [insin/nwb#318]
Running production build on a server results in error

`vendor.43103173.js:1 Uncaught SyntaxError: Unexpected token <`

with subsequent one saying:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at n ((index):15)
    at Object.0 (app.e637b463.js:40)
    at n ((index):15)
    at window.webpackJsonp ((index):15)
    at app.e637b463.js:1
```

It is referring to .call inside script that is present in index.html file
```
var o=t[r]={i:r,l:!1,exports:{}};return e[r].call
```

I have a feeling this might be related to: https://github.com/insin/nwb/issues/287

**Comment by IljaDaderko** [comment]
EDIT: this index file is produced by `yarn build` inside `/dist`

**Comment by insin** [comment]
The `<script>` in the generated HTML is the Webpack manifest, presumably things going south in the vendor bundle means module ids it's trying to access aren't there.

Which dependencies do you have installed? By default, anything imported from `node_modules/` goes into a `vendor` bundle. Wondering if a build with `NODE_ENV=development` set in your environment will reveal more.

**Comment by IljaDaderko** [comment]
Will drop list of dependencies below, strange thing is that I am able to start it on my local machine, yet once accessed via browser served from my server this error happens. Is there a chance code splitting could mess with this?

```
"dependencies": {
    "compression": "^1.6.2",
    "express": "4.15.3",
    "react": "16.0.0-alpha.12",
    "react-dom": "16.0.0-alpha.12",
    "react-helmet": "5.1.3",
    "react-loadable": "^3.3.1",
    "react-router-dom": "^4.1.1",
    "sanitize.css": "^5.0.0",
    "scrollmonitor": "^1.2.3",
    "styled-components": "2.0.0"
  },
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "15.0.1",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "2.3.0",
    "eslint-plugin-jsx-a11y": "5.0.3",
    "eslint-plugin-react": "7.0.1",
    "nwb": "0.16.3",
    "offline-plugin": "4.8.1",
    "prop-types": "15.5.10",
    "shipit-deploy": "^2.4.0"
  },
```

**Comment by IljaDaderko** [comment]
EDIT: it looks like vendor file is not present at all after CI build (ci now has same settings as my local machine) yet one builds it fine and other doesnt
