### ISSUE TITLE
Run react-component demo app over HTTPS with self-signed certificate

### ISSUE THREAD

**Issue by kylepeeler** [insin/nwb#321]
This issue is a: 

- [X] ? Bug report
- [X] ? Feature request
- [X] Question / support request
- [ ] Other

I am in the process of building a React Component Library that contains component wrappers around a Javascript Library my employer wrote, these components must run over HTTPS as the component brings in a javascript library that interacts with an API that only returns valid responses on HTTPS. Thus, I need the demo app to be served on HTTPS with a self-signed certificate. I tried making various changes to the nwb.config.js to no avail... any possible solution to this?

**Comment by insin** [comment]
You'll be able to use `devServer.https = true` config in the next release, which switches to Webpack Dev Server for the dev server.
