### ISSUE TITLE
Missing polyfill-ed prototypes when running in IE11.

### ISSUE THREAD

**Issue by jstralko** [insin/nwb#324]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [X] Question / support request
- [ ] Other

I'm having trouble poly filling Array.from using nwb toolkit.  I'm unsure who to configure nwb.config.js to tell Babel to polyfill it.  Do I need to add a preset or plugin?  It looks like fetch, Promise, and Object.assign work just fine, but Array.from and a few others are undefined when running my react application in IE11.  

my nwb.config.js is very minimal:

        module.exports` = {
    type: 'react-app',
    webpack: {
        define: {
            VERSION: JSON.stringify(require('./package.json').version),
            HOSTNAME: JSON.stringify(process.env.NODE_ENV === 'production' ?
                      'https://xyz.azurewebsites.net' :
                      'http://10.0.2.2:8080')
        },
        rules: {
            babel: {
                test: /\.jsx?/
            }
        },
        extra: {
            resolve: {
                extensions: ['.jsx']
            },
            devtool: '#inline-source-map'
        },
        html: {
            favicon: 'src/img/favicon.ico'
        }
    }
};

**Comment by insin** [comment]
You can add add additional polyfills as dependencies and import them before you kick your app off.

E.g. if you add [`core-js`](https://github.com/zloirock/core-js) as a dependency, adding `import 'core-js/fn/array/from'` to the top of `src/index.js` should do the trick. [Individual module polyfills](https://github.com/mathiasbynens/Array.from) are available too.

**Comment by jstralko** [comment]
Thanks for the help.  This is exactly what I was looking for.  Thank you for all your work on nwb.
