### ISSUE TITLE
HMR not working with custom port

### ISSUE THREAD

**Issue by axelboc** [insin/nwb#328]
This issue is a: 

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

I'm trying to customise the dev-server port, which I understand is possible thanks to PR #279, but I'm getting this in the browser console when I run `nwb serve-react-app --port 3333`:

![screen shot 2017-06-19 at 3 05 40 pm](https://user-images.githubusercontent.com/2936402/27270491-dcffedc8-5501-11e7-81d6-410a12c39412.png)

It keeps logging stuff continuously. Am I missing something? Here is a text version (for search engines) of the output a bit further down the logs:

> [HMR] Waiting for update signal from WDS...  only-dev-server.js:66
> POST XHR http://localhost:3333/193/enj4cgja/xhr_streaming [HTTP/1.1 404 Not Found 3ms]
> GET XHR http://localhost:3333/193/fiytg1pr/eventsource [HTTP/1.1 404 Not Found 3ms]
> Firefox can’t establish a connection to the server at http://localhost:3333/193/fiytg1pr/eventsource. eventsource.js:18
> GET http://localhost:3333/iframe.html#dddp1zl2 [HTTP/1.1 404 Not Found 2ms]
> [HMR] Waiting for update signal from WDS...  only-dev-server.js:66
> TypeError: u.getComputedStyle(...) is null[Learn More]  widgets.js:9:15499
> GET http://localhost:3333/iframe.html#tnq1uca1 [HTTP/1.1 404 Not Found 1ms]
> POST XHR http://localhost:3333/193/2fygeewc/xhr [HTTP/1.1 404 Not Found 1ms]
> GET http://localhost:3333/iframe.html#4eumfpap [HTTP/1.1 404 Not Found 2ms]
> POST XHR http://localhost:3333/967/hckwwxku/xhr_streaming [HTTP/1.1 404 Not Found 1ms]
> GET XHR http://localhost:3333/967/solocyrg/eventsource
> ...

I'm using:

- Node.js 6.9.3
- Yarn 0.24.6
- nwb 0.17.0

**Comment by insin** [comment]
v0.17.0 switched to Webpack Dev Server for `nwb serve...` comands - it looks like its client doesn't like the configuration we pass it when customising the host or port. Fix coming soon.

**Comment by insin** [comment]
Fixed in [v0.17.1](https://github.com/insin/nwb/releases/tag/v0.17.1) - thanks for reporting this!

**Comment by axelboc** [comment]
Awesome, thanks for the quick fix and release!
