### ISSUE TITLE
Issues using React Router in demo page locally with serve

### ISSUE THREAD

**Issue by SammyIsra** [insin/nwb#330]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

Hey! I am having issues with the demo page generated by `nwb` when using React Router. I am trying to navigate directly to the page `http://localhost:5000/stats` (not by following a link, but by tying that into the browser address bar) and I get a 404 error. However, if I follow the link that I put in `/`, then it works. 

I am using [serve](https://www.npmjs.com/package/serve) to serve the demo page for local testing. 

I am deploying to Surge.sh, and there it seems to work (when I change the name of `index.html` to `200.html`)

Relevant github file: https://github.com/SammyIsra/photostream-react/blob/5990da41cf5276d9f73a8ea7e402d5dbc5e0bdd2/demo/src/index.js
```
$ node -v
v6.10.0
$ npm -v
3.10.10
```

Modules installed in the project:
```
  "devDependencies": {
    "enzyme": "2.8.2",
    "nwb": "0.16.3",
    "react": "15.5.4",
    "react-addons-test-utils": "15.5.1",
    "react-dom": "15.5.4",
    "react-router-dom": "4.1.1",
    "react-test-renderer": "15.5.4",
    "serve": "5.2.2",
    "surge": "0.19.0",
    "whatwg-fetch": "2.0.3"
  },
```

Thank you!

**Comment by insin** [comment]
Are you passing a [`--single` flag](https://github.com/zeit/serve/blob/132f6626bfd6bc2e35163cb43d85ad294da3344e/bin/serve.js#L42) to `serve`?

**Comment by SammyIsra** [comment]
I was not, I just tried that and it worked. Thank you for helping with the small issue! 

Running `serve --single ./demo/dist` made it work as I was hoping it would.
