### ISSUE TITLE
nwb express middleware doesn't re-route `/`

### ISSUE THREAD

**Issue by IljaDaderko** [insin/nwb#338]
I added nwb middleware when running my project in dev mode, everything seems to work fine i.e. hot module reloading etc (although I disabled it by choice)

```
const nwb = require("nwb/express");
app.use(nwb(express, { entry: 'src/index.js', hmre: false, reload: true }));
``` 
One big issue I am facing is hitting refresh button when I have navigated somewhere like `/dashboard/payments`. When I do this I get express error saying `cannot GET /dashboard/payments` what is correct way to ensure that nwb middleware routs every request to `/` in order to use react-router?

**Comment by IljaDaderko** [comment]
Not sure if related, but re-compiling takes good 10 seconds to complete as well

**Comment by insin** [comment]
The middleware only handles requests which can be serviced by the Webpack development watcher - if your app needs an `/index.html` fallback in production you'll need to use [other middleware](https://github.com/bripkens/connect-history-api-fallback) for that yourself anyway, so also configure it for local development.

**Comment by IljaDaderko** [comment]
Was trying to re-route `"*"` to index.html file in public folder, worked with prod, but only history fallback middleware did the trick in dev, thank you :)
