### ISSUE TITLE
Useable style loader does not work after build

### ISSUE THREAD

**Issue by kirill-konshin** [insin/nwb#343]
This issue is a:

- Bug report

NWB version is 0.18.6.

If NWB is used with [useable styles loader](https://github.com/webpack-contrib/style-loader#useable) it works well in dev mode but throws an error if build is served.

### nwb.config.js

```js
module.exports = {
    type: 'react-app',
    webpack: {
        rules: {
            'sass-style': {
                loader: 'style-loader/useable'
            }
        }
    }
};
```

### src/index.js

```js
import React from "react";
import {render} from "react-dom";
import style from "./index.scss";

style.use(); // <----- this line will produce error in build version

const App = () => (<div>Foo</div>);
render(<App/>, document.getElementById('app'));
```

### src/index.scss

```scss
body {
    color: red;
}
```

## Steps to reproduce:

1. Build
2. Serve as static
3. Open browser
4. Observe error: `index.js:6 Uncaught TypeError: t.n(...).a.use is not a function`

**Comment by insin** [comment]
nwb uses [`ExtractTextPlugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin) to extract CSS in builds. According to these issues you can't extract usable styles:

- https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/25
- https://github.com/webpack-contrib/style-loader/issues/49

If you need to disable use of `ExtractTextPlugin` in builds, I could add setting [`webpack.extractText` config](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extracttext-object) to `false` as a way of disabling it.

**Comment by kirill-konshin** [comment]
> you can't extract usable styles
Totally makes sense

Previously it used to work w/o extra config... but if you can add a way of disabling this, please go ahead.

I think that `webpack.extractText: false|null` should be just enough: a strict check that if it's defined and is `falsy` then disable the plugin, but `undefined` will just use default config.

**Comment by insin** [comment]
If it used to work and the stylesheet was in an extra chunk you could try `webpack.extractText = {allChunks: false}` config - the default was changed to `true` a while back to avoid pulling the style-loader runtime into every build.

**Comment by kirill-konshin** [comment]
Yep, that's the case, it is working with `allChunks: false`. That's a very bad change, it's backward incompatible... I understand the rationale, but still...

In any case, I hope to see a setting to completely disable the extract text plugin because for useable styles case it is useless.

**Comment by kirill-konshin** [comment]
What will be the ETA of change?

**Comment by kirill-konshin** [comment]
Fix confirmed.
