### ISSUE TITLE
Building react app from node_modules/.bin

### ISSUE THREAD

**Issue by 01taylop** [insin/nwb#346]
This issue is a: 

- Question / support request

```
node v7.10.0
npm 5.3.0
nwb v0.18.7
```

I'm trying to build my react app in a docker container. Perhaps I'm being stupid (it is Friday and time to go home!) but the `entry` option does not seem to work.

```
nwb build-react-app [entry] [dist_dir]
    Build a React app from entry to dist_dir.
```

In node_modules/.bin, I am first calling `gulp build` which moves some assets from a different dependency, and runs sass-lint and es-lint. After that, I am trying to build the react app.

```
cd node_modules/.bin
./gulp build
./nwb build-react-app
```

I have tried `./nwb build-react-app ../../`, `./nwb build-react-app ../../src/index.js` but each time I get the same error:

```
Error: Cannot find module '/Users/x/y/z/node_modules/.bin/package.json'
```

The `dist_dir` works as expected, so `./nwb build-react-app ../../ ../../dist` will successfully delete my current '/dist' folder. Similarly, `./nwb check-config ../../nwb.config.js` tells me there is "Nothing to report!" in my config.

**Comment by insin** [comment]
nwb assumes it's being run from the project root and looks for `package.json` to check if you have any `nwb-*` plugins installed.

Running `./node_modules/.bin/nwb` from the root instead should work.

**Comment by 01taylop** [comment]
Ahh, of course. I didn't even think to try that on Friday, works perfectly. Thank you.
