### ISSUE TITLE
Support auto-installation of npm dependencies

### ISSUE THREAD

**Issue by insin** [insin/nwb#35]
Provide a built-in way to use @ericclemmons' [npm-install-loader](https://github.com/ericclemmons/npm-install-loader) for nicer developer experience.

Edit: or https://github.com/renke/auto-install-webpack-plugin

**Comment by insin** [comment]
Looks like this won't be as easy as hoped:

- npm-install-loader doesn't support CSS
- created an issue based on initial experimentation with auto-install-webpack-plugin: renke/auto-install-webpack-plugin#2

See ericclemmons/npm-install-loader#5 for a good discussion of this entire topic)

**Comment by ericclemmons** [comment]
I'm hoping that it _could_ support CSS because Webpack converts CSS to JS, but I need to experiment more.

Don't worry, we'll get it figured out (@renke or myself).
