### ISSUE TITLE
Add built-in prettier

### ISSUE THREAD

**Issue by xuopled** [insin/nwb#353]
This issue is a: 
- Feature request

It should be great to add prettier to generated templates.

For example for a generated react component:

```package.json
"scripts": {
    "precommit": "lint-staged"
},
"devDependencies": {
    "husky": "^0.14.3",
    "lint-staged": "^4.0.2",
    "prettier": "^1.5.3"
},
"lint-staged": {
    "*.js": [
      "prettier --no-bracket-spacing --no-semi --trailing-comma=es5 --write",
      "git add"
    ]
}
``` 

In case you add [built-in linting](https://github.com/insin/nwb/issues/157):

```.eslintrc
{
  "plugins": [
    "prettier"
  ],
  "extends": [
    "prettier"
  ]
}

```

**Comment by xuopled** [comment]
Instead of define lint-staged config in package.json, you can define a `.lintstagedrc` with:
```
{
  "*.js": [
    "prettier --no-bracket-spacing --no-semi --trailing-comma=es5 --write",
    "git add"
  ]
}
```

**Comment by insin** [comment]
The opinions prettier lets you configure are the same ones I removed the original ESLint config to avoid forcing on people, so I think adding it to the templates would make them a bit too opinionated.
