### ISSUE TITLE
AngularJS and Angular generators

### ISSUE THREAD

**Issue by jamrizzi** [insin/nwb#362]
Is there any interest in support for Angular and AngularJS?

**Comment by insin** [comment]
From having used Angular and angular-cli recently, no, everything which would need to be added would be completely Angular-specific and I'm not interested in writing or maintaining it.

**Comment by jamrizzi** [comment]
Hmmm, ok I'll just have to fork it and maintain my own branch then. I wish this was more modular and I could do this with a plugin, but oh well.
