### ISSUE TITLE
Unexpected token: operator (>) [./node_modules/json.sortify/lib/index.js:29,0][demo.9eaa1091.js:44563,20]

### ISSUE THREAD

**Issue by tnrich** [insin/nwb#366]
Hey there I'm getting the following issue when running on node v7. Uglify appears to be choking on an arrow function which should be fully supported in node v7. Any thoughts on how to fix this or disable uglify for the time being?

Unexpected token: operator (>) [./node_modules/json.sortify/lib/index.js:29,0][demo.9eaa1091.js:44563,20]

Thanks!

**Comment by insin** [comment]
You can disable uglify by configuring [`webpack.uglify = false`](https://github.com/insin/nwb/blob/master/docs/Configuration.md#uglify-object--false).

Uglification of ES6+ will work in nwb v0.21 (see #412)
