### ISSUE TITLE
Babel runtime in dev (redux DockMonitor) - npm3

### ISSUE THREAD

**Issue by geowarin** [insin/nwb#37]
When using redux dev tools, I get the following error:

```
ERROR in ./~/react-dock/lib/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/geowarin/dev/react/nwb-tests/test-app/node_modules/node_modules/babel-runtime/helpers/interop-require-default in /Users/geowarin/dev/react/nwb-tests/test-app/node_modules/react-dock/lib
 @ ./~/react-dock/lib/index.js 3:29-85
```

This path is strange: /node_modules/node_modules/babel-runtime.
The other thing is it cannot be reproduced when nwb is installed locally and linked with `npm link`.

My guess is that there is something wrong with [this config](https://github.com/insin/nwb/blob/0c76e581964c683f6d82e0287e58e542744e07bc/src/createWebpackConfig.js#L361).

Repro here:
https://travis-ci.org/geowarin/test-app/builds/99708029

Supporting both npm 2 and 3 looks like a chore.

**Comment by insin** [comment]
Time to sort out some proper testing for npm3

**Comment by insin** [comment]
I didn't expect dependencies to be pulling in babel-runtime, so I think that blows my approach of using aliases to make it resolvable from the app out of the water.

**Comment by insin** [comment]
I'm unable to replicate this locally in Linux, with any combination of local and global installation using Node 5/npm3, but I'm going to change the approach for getting a hold of babel-runtime to use webpack's fallback feature in any case.
