### ISSUE TITLE
Unable to install globally with npm 5.4.0

### ISSUE THREAD

**Issue by daoxxx** [insin/nwb#383]
This issue is a: 
- Bug report

Is the version of `nwb` you're using installed globally or locally?

Globally

Which versions of Node.js, npm and nwb are you using (if using it globally)?
Node.js 6.11.2
npm 5.4.0

An error occurs when i'm trying to install nwb though
sudo npm install -g nwb

This is exactly the same problem as the issue [https://github.com/insin/nwb/issues/345](https://github.com/insin/nwb/issues/345) stated, stumbling upon installation of Phantomjs.

After downgrading npm to version 3.10.10 nwb installed successfully.

**Comment by rguderlei** [comment]
The --unsafe-perm option does the trick. See  https://github.com/Medium/phantomjs/issues/707

**Comment by daoxxx** [comment]
Thank you.
As a newbie, I didn't know what Phantomjs is needed for, so i moved to create-react-app.
