### ISSUE TITLE
0.19.0 breaks test setup

### ISSUE THREAD

**Issue by mikkelwf** [insin/nwb#389]
Upgrading to 0.19.0 from 0.18.10 breaks my test setup

Error:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: react
  at webpack:/external%20%22react-dom%22:1:0 <- tests.webpack.js:211616

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.883 secs / 0 secs)
```

nwb config 
```
module.exports = {
  type: 'react-app',

  webpack: {
    compat: {
      enzyme: true,
      sinon: true
    }
  },

  karma: {
    testContext: 'tests.webpack.js',
    reporters: [
      require('karma-spec-reporter')
    ],
    extra: {
      specReporter: {
        maxLogLines: 15,
        suppressErrorSummary: false,
        suppressFailed: false,
        suppressPassed: false,
        suppressSkipped: false,
        showSpecTiming: true
      }
    }
  }
}
```
tests.webpack.js
```
import sinon from 'sinon'
import chai from 'chai'
import sinonChai from 'sinon-chai'
import chaiAsPromised from 'chai-as-promised'
import chaiEnzyme from 'chai-enzyme'
import 'whatwg-fetch'

chai.use(sinonChai)
chai.use(chaiAsPromised)
chai.use(chaiEnzyme())

global.chai = chai
global.sinon = sinon
global.expect = chai.expect

let context = require.context('./src', true, /\.spec\.js$/)
context.keys().forEach(context)
```

Including and exposing react in `tests.webpack.js` only throws a new error:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: dom
  at webpack:/external%20%22react-dom%22:1:0 <- tests.webpack.js:211616

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.883 secs / 0 secs)
```

I think i has something to do with removing the hooking of React, but i have no idea how to fix my test setup..

Help is much appreciated..

**Comment by insin** [comment]
Which versions of all the React packages and Enzyme are you using?

The hooking stuff was about the `nwb react` command trying to handle all render() calls, so shouldn't affect this.

This should have been the only relevant change but now that Enzyme 3 is out, it's not even in the Enzyme guide docs I took it from: https://github.com/insin/nwb/commit/5172ccdc2a6b1f4bf11dcb7a98f552ea332c2c3c

**Comment by mikkelwf** [comment]
I was on react 15.6.1 and enzyme 2.9.1..
But i managed to upgrade to setup to react 16 and enzyme 3, and now everything works..

So i'm closing this issue since i think it only applies to my (now previous) setup.

Sorry to bother :)

**Comment by insin** [comment]
No problem, I'm going to back out the change anyway and mark the `enzyme` compat stuff as deprecated now that Enzyne 3 is out and supports all versions of React.
