### ISSUE TITLE
Dropping support for Node.js 4

### ISSUE THREAD

**Issue by insin** [insin/nwb#400]
Node.js 4 [exits LTS Maintenance in April 2018](https://github.com/nodejs/Release#nodejs-release-working-group).

- [x] Bump babel-preset-env config to Node 6
- [x] Inquirer.js will need to be pinned to 3.3.0 until we're ready to drop support, as it[ dropped support for Node.js 4 in 4.0.0](https://github.com/SBoudrias/Inquirer.js/releases/tag/v4.0.0)

**Comment by Sharlaan** [comment]
How about going directly to Node 8.9 LTS ?
This version of Node seems to support everything except modules still under flag --expermimental-modules
Doing so would allow NWB to ship fully transpiled version in lib/, while native untranspiled in es/ ? (at exception of import/export)

**Comment by insin** [comment]
Webpack 4 is dropping support for Node.js 4: webpack/webpack#6064

**Comment by insin** [comment]
webpack-dev-middleware has dropped support for Node.js 4: https://github.com/webpack/webpack-dev-middleware/pull/233
