### ISSUE TITLE
nwb build-react-app always returns with exit code of 0

### ISSUE THREAD

**Issue by jstralko** [insin/nwb#405]
This issue is a: Bug Report

node -v
v6.11.2
npm -v
3.10.10
nwb -v
v0.15.2

When running nwb build-react-app it always returns with exit code 0 regardless if there were errors or not.  So my scripts don't get reported if there is an error. 

i.e.

✖ Building React app

Failed to compile with 1 error.

 ERROR  in ./src/components/LineGraph.jsx
Module not found: Error: Can't resolve 'd3' in '/Volumes/Source/src/components'
 @ ./src/components/LineGraph.jsx 19:0-25
 @ ./src/index.js
 @ multi /usr/local/lib/~/nwb/polyfills.js ./src/index.js

Then doing:
$>echo $?
0

It would be nice to get something other than 0 when there is an error.

**Comment by insin** [comment]
Just spotted the version - this was fixed for #290 in v0.17

**Comment by jstralko** [comment]
Thank you very much!
