### ISSUE TITLE
json files do not get copied over in build-react-component

### ISSUE THREAD

**Issue by redbmk** [insin/nwb#407]
This issue is a: 

- Bug report
- Question / support request

I built a component using `nwb new react-component my-component`. In a few places in `src` I have a few `.json` files, which I can import with `import asdf from './asdf.json'` and it works just fine when running the demo with `yarn start`.

However, when I go to build the component with `yarn build` the `.json` files are missing from the `es` and `lib` folders, so the files fail to import when used elsewhere.

The workaround I found for now is a somewhat messy bash oneliner, which I then added to `package.json` as a `postbuild` so it gets run automatically after the build.

```bash
find src -name '*.json' | grep -o '/.*' | xargs -I% bash -c 'cp src% es%; cp src% lib%'
```

```diff
diff --git a/package.json b/package.json
index b72d65a..5a20d7e 100644
--- a/package.json
+++ b/package.json
@@ -13,6 +13,7 @@
   ],
   "scripts": {
     "build": "nwb build-react-component",
+    "postbuild": "find src -name '*.json' | grep -o '/.*' | xargs -I% bash -c 'cp src% es%; cp src% lib%'",
     "clean": "nwb clean-module && nwb clean-demo",
     "start": "nwb serve-react-demo",
     "test": "nwb test-react",
```

It would be awesome if I didn't have to do this. Is there a config I missed somewhere, or is this a bug?

**Comment by insin** [comment]
There's a [`--copy-files` flag](https://github.com/insin/nwb/blob/master/docs/Commands.md#react-componentlibrary-and-web-module-builds) you can use for this - those docs could do with some headers to make the flags stand out more.

**Comment by redbmk** [comment]
Nice, that did the trick! Thanks @insin. I kept searching for `json` in the docs and didn't see anything. I think it would have helped me if instead of

> such as CSS files

it said

> such as CSS or JSON files

Maybe adding some more examples would help other people.

**Comment by insin** [comment]
Hopefully this is a little easier to find now

**Comment by redbmk** [comment]
Awesome, thanks for the quick update!
