### ISSUE TITLE
How to specify 3rd party preprocessors for karma in web-module build's config?

### ISSUE THREAD

**Issue by adam-digirati** [insin/nwb#408]
I was trying to configure nwb with karma-html2js-preprocessor with the following configuration:

```
module.exports = {
  type: 'web-module',
  npm: {
    esModules: true,
    umd: false
  },
  karma: {
    preprocessors: {
      'tests/data/**/*.html': ['html2js']
    },
    testFiles: [
      'tests/data/**/*.html'
    ],
    html2JsPreprocessor: {
      stripPrefix: 'tests/data/',
      processPath: function(filePath) {
        return filePath.replace(/\.html$/, '');
      }
    }
  }
}
```

Seemingly, the both the `preprocessors` and the `html2JsPreprocessor` are completely ignored. As I can see, the `getKarmaPluginConfig()` has only hardwired preprocessors config:

```
var preprocessors = {};

  if (userKarma.testContext) {
    files.push(userKarma.testContext);
    preprocessors[userKarma.testContext] = ['webpack', 'sourcemap'];
  } else {
    testFiles.forEach(function (testGlob) {
      files.push(testGlob);
      preprocessors[testGlob] = ['webpack', 'sourcemap'];
    });
  }
```
I understand that nwb karma config is not the same as the raw karma config because it's being transformed. Do you guys have a workaround for this? Am I missing something? Is there any way to configure nwb karma with 3rd party pre-processors?

**Comment by adam-digirati** [comment]
In case anybody having the same issue, I ended up using the webpack html-loader plugin and import the required files as a string.

```
module.exports = {
  type: 'web-module',
  npm: {
    esModules: true,
    umd: false
  },
  webpack: {
    extra: {
      module: {
        rules: [{
          test: /\.html$/,
          exclude: /node_modules/,
          use: {loader: 'html-loader'}
        }]
      }
    }
  }
}
```
And instead of refferring the contents from 

`window.__html__['expected.html']`

simply used

`import expectedHTML from './expected.html';`


This solves the problem for the original example above. Also, it seems to be a much more elegant solution. But still, it would be great if we could add 3rd party karma preprocessors to the nwb config.

**Comment by insin** [comment]
You can use [`karma.extra`](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extra-object-1) to add any arbitrary extra stuff to be merged into the generated config.

I should also add the same [config function escape hatch that's available for Webpack config](https://github.com/insin/nwb/blob/master/docs/Configuration.md#config-function) for Karma config, which would allow you to edit the generated config programmatically.

**Comment by adam-digirati** [comment]
Thanks. I failed to spot the`karma.extra`.
