### ISSUE TITLE
Webpack's DefinePlugin not working with react-component

### ISSUE THREAD

**Issue by trevorhalvorson** [insin/nwb#410]
I'm trying to set environment variables via [Webpack's DefinePlugin](https://github.com/insin/nwb/blob/master/docs/Configuration.md#define-object).

Create project: `nwb new react-component react-loading-button`

Update `nwb.config.js`:

```
module.exports = {
  type: 'react-component',
  npm: {
    esModules: true,
    umd: false
  },
  webpack: {
    define: {
      REACT_APP_MY_ENV_VAR: 'test',
    },
  },
}
```

Expected: After build/start `process.env.REACT_APP_MY_ENV_VAR` has value `'test'`
Actual: `process.env.REACT_APP_MY_ENV_VAR` is `undefined`

-----

**Is the version of `nwb` you're using installed globally or locally?**

globally

**Which versions of Node.js, npm and nwb are you using (if using it globally)?**

```
node -v
6.10.0
npm -v
5.5.1
# If nwb is being used as a global install
nwb -v
v0.20.0
```

**Comment by insin** [comment]
You need to define the full expression` DefinePlugin` will replace with the given value, so try `'process.env.NODE_ENV': JSON.stringify('test')` instead

**Comment by trevorhalvorson** [comment]
Thanks, it's working as expected.
