### ISSUE TITLE
Express + NWB hot reloading in a web-app application

### ISSUE THREAD

**Issue by Lc0rE** [insin/nwb#414]
This issue is a: 

- [ ]  Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

## Description
I'm trying to use the `nwb/express` middleware in order to combine my Node (Express) server with the client part bootstrapped with NWB.
Before getting hands dirty on the big project, I'm testing on the simplest possible configuration and, of course, I'm not able to make it work :P

I just added a `server.js` file with the basic configuration in the root file of my nwb web-app project:

```js
var express = require('express');

var app = express()

app.use(require('nwb/express')(express, options = {
  reload: false
}))

app.use(express.static('public'))

app.listen(3000, function(err) {
  if (err) {
    console.error('error starting server:')
    console.error(err.stack)
    process.exit(1)
  }
  console.log('server listening at http://localhost:3000')
})
```

The middleware works just fine but the hot reloading module doesn't seem to work.
If I edit my `src/index.js` file, I receive a success message on my console:

```bash
Recompiling...
Compiled successfully in 69 ms.
```

but on the browser console:
```bash
process-update.js:22 Ignored an update to unaccepted module ./src/index.js -> 0
onUnaccepted @ process-update.js:22
hotApply @ bootstrap da22f3c8a077a60ce375:438
cb @ process-update.js:66
(anonymous) @ process-update.js:82
Promise resolved (async)
check @ process-update.js:81
./node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:42
processMessage @ client.js:243
handleMessage @ client.js:126
handleMessage @ client.js:89
process-update.js:95 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.
logUpdates @ process-update.js:95
applyCallback @ process-update.js:63
(anonymous) @ process-update.js:71
Promise resolved (async)
cb @ process-update.js:70
(anonymous) @ process-update.js:82
Promise resolved (async)
check @ process-update.js:81
./node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:42
processMessage @ client.js:243
handleMessage @ client.js:126
handleMessage @ client.js:89
process-update.js:103 [HMR]  - ./src/index.js
```

Again, if I'm going to try and edit the `index.html` file, I get:
```js
[HMR] bundle rebuilding
client.js:222 [HMR] bundle rebuilt in 69ms
process-update.js:41 [HMR] Checking for updates on the server...
process-update.js:112 [HMR] Nothing hot updated.
process-update.js:121 [HMR] App is up to date.
```

But nothing happens!

If 'm passing the option `reload: true` to my middleware, the page is reloading (without the HMR...).

What am I missing?

**Comment by insin** [comment]
You'll need to use the [Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement) API to manually accept HMR requests.

```js
if (module.hot) {
  module.hot.accept('./someModule', () => {
    // Do stuff
  )
}
```

The web-app template doesn't contain any default HMR code because it doesn't know what your app is going to to (whereas React projects use a Babel plugin to accept HMR requests and Inferno/Preact projects re-render the app from the top by default).
