### ISSUE TITLE
html-webpack-plugin 2.x

### ISSUE THREAD

**Issue by jantimon** [insin/nwb#42]
As you are using the plugin in your npm packages I just wanted to let you know that I am planing to release html-webpack-plugin 2.x soon:
https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders

It allows to pre render react on the server side.

**Comment by insin** [comment]
@jantimon thanks for the heads-up. Is there a changelog anywhere of what's breaking/new/changed in 2.x?

**Comment by jantimon** [comment]
Not yet - the main different is the way how the template is compiled.
It uses a webpack child compiler with lodash templates instead of blueimp templates.
As it uses loaders it is now able to move and hash assets and include partials.

**Comment by insin** [comment]
Sounds great :)

**Comment by insin** [comment]
Included in v0.8.0
