### ISSUE TITLE
devServer.port is ignored in config

### ISSUE THREAD

**Issue by kirill-konshin** [insin/nwb#423]
This issue is a: Bug report

On latest NWB if config exports the following the port is still 3000:

```js
module.exports.devServer = {
    port: '8080'
};
```

Based on following docs it should work: https://github.com/insin/nwb/blob/master/docs/Configuration.md#dev-server-configuration and https://webpack.js.org/configuration/dev-server/#devserver

Is there any other way to configure port from JS?

**Comment by insin** [comment]
Some of the `devServer` options are only used by webpack-dev-server's CLI, which nwb isn't using, so you currently you have to pass a [`--port` option](https://github.com/insin/nwb/blob/master/docs/Commands.md#nwb-serve) to the `nwb serve` command instead.

`devServer` config is available when nwb is starting the server, so we can can also add support for using `devServer.port` if it's configured.

**Comment by kirill-konshin** [comment]
Yes of course I am aware of —port CLI param, but it’s not always convenient. It would be great if config will be respected )

**Comment by kirill-konshin** [comment]
Wow that was fast! Thanks! When to expect NPM release?

**Comment by insin** [comment]
Should be later today, there are some dependency updates I want to include as well.

**Comment by kirill-konshin** [comment]
Found a weirdest bug on version `0.21.3`.

When I run with `exports.devServer.port = '8080'` I get:

```
Something is already running on port 8080.
? Would you like to run the app on another port instead? (Y/n) 
```

Notice that port `8080` is in the message. I double checked `http://localhost:8080` and `$ lsof -i tcp:8080` — there's nothing running.

But when I do `nwb serve-react-app --port 8080` everything just works even without changing the config :) how weird...
