### ISSUE TITLE
uglify not working.

### ISSUE THREAD

**Issue by bebbi** [insin/nwb#428]
This issue is a: 
- Question / support request

`nwb build-web-module  --no-demo` builds a module but doesn't uglify. Same var names, newlines, comments, just ES5.

Nothing helped (reading docs, setting `NODE_ENV=production nwb ...`, adding uglifyjs config object into nwb.config.js). I can see webpack object when running in debug mode.

Just wondering if there's something I'm not seeing?

Is the version of `nwb` you're using installed globally or locally?

global

Which versions of Node.js, npm and nwb are you using (if using it globally)?

```
node -v
v8.9.1
npm -v
5.6.0
# If nwb is being used as a global install
nwb -v
v0.21.5
```

Which modules are installed in your project?
dev: cross-env, npm-watch
dep: myscope/somedep.

Using yarn & workspaces.

**Comment by insin** [comment]
Do you mean the output in `lib/` and `es/`? Currently, it's expected that if you're using a module in an app, it will handle minification as part of its build process.

If/when nwb switches to using Rollup for npm module builds (#316) we may look at adding support for development/production bundles where one of the bundles is minified.

**Comment by bebbi** [comment]
Thanks! Yes, i was hoping for doing a slight cleanup incl. saving unnecessary code for an app and thought I could use the uglify options to trigger bundling as well, my misunderstanding.
