### ISSUE TITLE
copy-webpack-plugin broken?

### ISSUE THREAD

**Issue by mikkelwf** [insin/nwb#431]
This issue is a: Bug report / Question

I cannot seem to get copy-webpack-plugin to work.

I've configured my config like this: 
```
module.exports = {
  type: 'react-app',

  ...

  webpack: {
    copy: {
      options: {
        debug: true
      },
      patterns: [
        {from: 'src/static/robots.txt', to: 'dist/robots.txt'},
        {from: 'src/static/manifest.webmanifest', to: 'dist/manifest.webmanifest'},
        {from: 'src/static/sitemap.xml', to: 'dist/sitemap.xml'}
      ]
    }
  }
}
```

I tried to console log around this line
https://github.com/insin/nwb/blob/868577291415f9943b4f6239bf09813a9917057e/src/createWebpackConfig.js#L625

```
console.log(buildConfig.copy, userConfig.copy);
```

`userConfig.copy` contains what I put in the config, `buildConfig.copy` is undefined.

I've tried running `yarn run build --copy-files` as well, `buildConfig.copy` is still undefined.

So how does this work..?

**Comment by mikkelwf** [comment]
I read the documentation again and figured out that I had to use the `public/` folder, which is pretty nice.

To avoid this confusion for other, might I suggest to add a note to the documentation that states that the additional patterns only work if you at least copy one file from the `public/` folder?

**Comment by dmk255** [comment]
I've had luck running the following as my build step. I've stopped trying to use the copy plugin.
```
nwb build-react-component --copy-files && rm -rf es/**/__mocks__ && rm -rf lib/**/__mocks__ && rm -rf es/__mocks__ && rm -rf lib/__mocks__
```

**Comment by insin** [comment]
> I read the documentation again and figured out that I had to use the `public/` folder, which is pretty nice.

This is a bug - we're currently conditionally enabling the `CopyPlugin` based on the presence of a `public/` dir, but it should also be added if the user configured something in `webpack.copy`.
