### ISSUE TITLE
include prepare scripts for npm-modules & react-components

### ISSUE THREAD

**Issue by hanford** [insin/nwb#436]
This issue is a:

- Feature request

It's pretty common to utilize npm's lifecycle commands .. In my case, I'd love `react-components` and `npm-modules` I bootstrap with `nwb` to include a [prepare script](https://docs.npmjs.com/misc/scripts#description) that simply invokes `npm run build` ensuring that whenever I publish a new version, my new code will be rebuilt.

Is this something that has been considered? I'd love to open a PR if it's welcome.

Cheers!

**Comment by insin** [comment]
@hanford Yes, a PR would be most welcome 😸

**Comment by hanford** [comment]
@insin wasn't sure if I was supposed to base off of the `next` branch or `master`, I can redo the PR on `next` if `master` was incorrect.

Cheers! 🍻
