### ISSUE TITLE
Ant-design example?

### ISSUE THREAD

**Issue by RaedsLab** [insin/nwb#443]
This issue is a:
- Feature request
- Question / support request

Is there a way to have a working config example with [ant](https://github.com/ant-design/ant-design/) ?

**Comment by insin** [comment]
Created a CSS-importing example here: https://github.com/insin/nwb-examples/tree/master/react-app-antd

It should also be possible to use the Less version too using nwb-less and nwb's support for [configuring stylesheet preprocessors](https://github.com/insin/nwb/blob/master/docs/Stylesheets.md#stylesheets) - will have a look at that when I get some time.

**Comment by RaedsLab** [comment]
Thank you very much, the CSS version works! 

I'm overriding some less variables with ant, and would really appreciate your help getting less to work.

**Comment by insin** [comment]
The example has been updated to show both regular CSS and Less with modified vars, plus it's now linked to from the Ant Design docs: https://ant.design/docs/react/use-with-create-react-app#Source-code-and-other-boilerplates

**Comment by RaedsLab** [comment]
Thank you this works perfectly.
