### ISSUE TITLE
SVG file not being loaded in build

### ISSUE THREAD

**Issue by raed667** [insin/nwb#446]
- Bug report
- Question / support request

I would like to include an SVG in my react component. whenever I build the project the output does not include my svg file even if its under /src.

[Project](https://github.com/RaedsLab/nwb-component-svg )

```
npm ls --depth=0
```
+-- nwb@0.21.5
+-- react@16.2.0
`-- react-dom@16.2.0

**Comment by manglobe** [comment]
use `nwb build-react-component --copy-files`?
