### ISSUE TITLE
issue: "Import in body of module; reoder to top", thrown by CRA next branch.

### ISSUE THREAD

**Issue by bebbi** [insin/nwb#450]
This issue is a: 

- Bug report

For my module, nwb has created an `es` folder with an `index.js` file starting as follows:

        var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

        import { myThing } from '@myprefix/mylib'
        // etc.

I'm using this in a monorepo together with `create-react-app` next branch `2.0.0-next.b2fd8db8`.

Running a CRA app with a dependency on my nwb lib errors out with

`error  Import in body of module; reorder to top`

I just confirmed this does not happen with `react-scripts` version `1.1.2`, it will run fine.

I'm posting this here for now as I believe the error thrown by CRA is valid.

I will look at a repro in case this is not an obvious issue.

Is the version of `nwb` you're using installed globally or locally?

global

Which versions of Node.js, npm and nwb are you using (if using it globally)?

```
node -v 8.9.1
npm -v 5.7.1
# If nwb is being used as a global install
nwb -v 0.21.5
```

Which modules are installed in your project?

n.a. I think as the bug is triggered at a consumer.

**Comment by insin** [comment]
Does that mean CRA 2.0 is running `eslint` on code imported `node_modules/`? That doesn't seem right, but I can't see any relevant open issues in the CRA repo.

**Comment by insin** [comment]
It looks like projects created with `create-react-app@next` don't use `react-scripts@next` (the test project I created used `react-scripts@1.1.2`), so it doesn't have [this change](https://github.com/facebook/create-react-app/commit/b43ad04b880f460ed23dbb7968bae634bf7dbc91) which excludes `node_modules` from eslint checking.

**Comment by bebbi** [comment]
I thought it's related to CRA@next introducing monorepo support, and there, being able to source code from below its own root. The offending code is then be in the nwb module `es` 
directory, not in node_modules.

**Comment by bebbi** [comment]
You can pass `--react-scripts 2.0.0-next.b2fd8db8` to the cra binary to use the @next scripts

**Comment by gaearon** [comment]
Sounds like this should be a CRA bug report instead?

**Comment by insin** [comment]
> The offending code is then in the nwb module `es` directory, not in node_modules.

Ah, I missed the significance of the monorepo part - is there a way to configure it so CRA uses `your-module/src` instead of letting webpack hit `package.json` and picking up the `module` build from `es/`? I hadn't considered how this would work in monorepos.

**Comment by bebbi** [comment]
@gaearon I don't know enough details, filed here because it seemed that es modules should satisfy the `imports on top` requirement.

I'll file it at CRA instead.
