### ISSUE TITLE
nwb build-web-module and env vars

### ISSUE THREAD

**Issue by AquiGorka** [insin/nwb#456]
This issue is a: Question / support request

Great library and many thanks for all the work.

I see you removed support for `env` variables [here](https://github.com/insin/nwb/commit/65a212f2c713f897ef6d434fbf8cdafc3a5631ad), is there any way to build a `web-module` that can use an `env` var?

Use case:  a value for `dev` environment and a different one for `prod`.

**Comment by kirakik** [comment]
@AquiGorka did you figure out a way around this?

**Comment by AquiGorka** [comment]
@kirakik I did not and in the end used [`create-react-app`](https://github.com/facebook/create-react-app) which has built-in support for `env` vars.

**Comment by fc** [comment]
In your `nwb.config.js` file, use the `extra` option to add webpack's environment plugin:
```
const webpack = require("webpack");

module.exports = {
  type: "react-component",
  npm: {
    esModules: true,
    umd: {
      global: "SomeApp",
      externals: {
        react: "React"
      }
    }
  },
  webpack: {
    extra: {
      plugins: [
        new webpack.EnvironmentPlugin({
          BLAH: "aha"
        })
      ]
    }
  }
};
```

In the above example, access it as `process.env.BLAH`

Reference:
https://github.com/insin/nwb/blob/master/docs/Configuration.md#extra-object


If you wanted to use `dotenv`, you could also use it like so (untested):
```
import dotenv from 'dotenv';

/* etc */

    new webpack.EnvironmentPlugin({
      ...dotenv.config().parsed
    }),
```
