### ISSUE TITLE
ES6 module import throwing a weird error

### ISSUE THREAD

**Issue by samrith-s** [insin/nwb#472]
This issue is a:
- Question / support request

Demo:
https://codesandbox.io/s/wox95vknqw

These checks might help you diagnose whether something is wrong with nwb or your setup:

Is the version of `nwb` you're using installed globally or locally?
Locally

Which versions of Node.js, npm and nwb are you using (if using it globally)?

```
node -v
npm -v
# If nwb is being used as a global install
nwb -v
```
![image](https://user-images.githubusercontent.com/9032162/44001212-76d23f62-9e4b-11e8-8bf6-92a05d7b5d75.png)

Which modules are installed in your project?
```
npm ls --depth=0
```
![image](https://user-images.githubusercontent.com/9032162/44001205-565cc0b8-9e4b-11e8-8d6f-b33402cb90d8.png)

---

The question is, in the code sandbox, importing my package as an ES6 module works. But in my work project, if I do
`import { Table, Column } from 'sticky-react-table'`, ESLint throws the following error:
![image](https://user-images.githubusercontent.com/9032162/44001253-356e925e-9e4c-11e8-8706-a61985a27996.png)
This is mind-boggling. I have tried a whole lot of different configs, etc. Still doesn't resolve this.

Any help would be greatly appreciated and sorry if this is an irrelevant issue. I'm grasping at straws here.

Cheers!

**Comment by insin** [comment]
It doesn't look like there's anything wrong with your published package: https://unpkg.com/sticky-react-table@0.0.17/

From the stackt race, it looks like an issue with the eslint setup in the project you're trying to use it in.

**Comment by samrith-s** [comment]
Hey @insin, thanks a lot for the reply. The problem was indeed with out ESLint setup.

For the record if anybody else faces this problem in the project which uses your package, you might wanna check if the project uses `eslint-plugin-import`.

If it does, just add your package in the `import/core-modules` of your `.eslintrc` file like so:
![image](https://user-images.githubusercontent.com/9032162/44302553-ab32b500-a348-11e8-9ebf-66ad3f99e6ad.png)
