### ISSUE TITLE
How to use font from npm 

### ISSUE THREAD

**Issue by tnrich** [insin/nwb#479]
Hey there @insin ,

I'm trying to use the "Ubuntu Mono" font family. I've npm installed the following package: 

https://github.com/KyleAMathews/typefaces/tree/master/packages/ubuntu-mono

and have added a `require('typeface-ubuntu-mono')` to my index.js file. 

But unfortunately it doesn't seem to be getting recognized. Is nwb set up to handle this kind of thing sans config? It says this on the readme
>Many tools built with Webpack will work out of the box with Typefaces such as Gatsby and Create React App.

Any pointers or ideas? 
Thanks!

**Comment by tnrich** [comment]
Hmm looks like it might just be specific to that specific font, Ubuntu Mono.. I'll look into it more and let you know.

**Comment by tnrich** [comment]
whoops... spelling error! I was trying to load
```
/* font-family:  "Ubunto Mono"; */
```
instead of:
```
/* font-family:  "Ubuntu Mono"; */
```


cuh-lassic!

**Comment by mikhuang** [comment]
Glad you resolved your issue. It might be useful for others if this could be closed?
