### ISSUE TITLE
Source map not working?

### ISSUE THREAD

**Issue by amarandon** [insin/nwb#48]
Are source maps meant to work out of the box? It doesn't seem to be the case here... In browser error reporting also has 404 links to source code, which might be related.

With this code:

```js
import React from 'react'
import Icon from 'react-fa'

export default React.createClass({
  render() {
    foo(bar);
    return <div>
      <h2>Welcome to React!</h2>
      <Icon spin name="edge" />
    </div>
  }
})
```
I get this in the browser:

![nwb_error_reporting](https://cloud.githubusercontent.com/assets/101934/12221380/42d2cbe6-b799-11e5-993f-204716a6a128.png)

I would expect error reporting to point at my code rather than at the bundled code.

**Comment by insin** [comment]
It's currently using `devtool: '#evail-source-map'`, but reading around, it seems like we'll need to switch to `'eval'` to get the correct filenames.

**Comment by amarandon** [comment]
This may be related to https://github.com/webpack/webpack/issues/1194

**Comment by insin** [comment]
Source maps work for me in Firefox 43.0.4 in Debugger > Sources, showing the transpiled code with `nwb serve` and the original source with `nwb build`, but not in stack traces.

![nwb-source-map](https://cloud.githubusercontent.com/assets/226692/12223587/b29dced2-b7d3-11e5-8539-8f77b87e9aa0.png)
![nwb-source-map-serve](https://cloud.githubusercontent.com/assets/226692/12223593/dbe489ac-b7d3-11e5-9b9c-7f5ac65b6153.png)

**Comment by amarandon** [comment]
Yes it's a Firefox issue, talking about it to the developer: https://twitter.com/alex_marandon/status/686514228572864512
Redbox is a different issue. I suppose it's fine to close this one.
