### ISSUE TITLE
How to stop nwb new react-app initialising a git repo?

### ISSUE THREAD

**Issue by agoodsell5** [insin/nwb#484]
This issue is a: 

- Question / support request
How do I stop nwb new react-app from initializing a new git repository? I am running this command naturally from within an existing repo, and it is there creating a repo within a repo, which is not desired at all!
![nwbissue](https://user-images.githubusercontent.com/16920460/46139004-589cc080-c245-11e8-893f-1f495779d216.PNG)

**Comment by lsmoura** [comment]
`$ nwb --help`

Output highlight:

```
  Options:
    -f, --force   force project creation, don't ask questions
    --es-modules  enable or disable (--no-es-modules) an ES modules build
    --no-git      disable creation of a Git repo with an initial commit
    --react       version of React to install for React apps & components
    --umd=<var>   enable or disable (--no-umd) a UMD build
```
