### ISSUE TITLE
can't resolve `./x.css` in lib?

### ISSUE THREAD

**Issue by a-eid** [insin/nwb#494]
This issue is a question / support request 

after building and publishing I get an error that `x.css` file can't be resolved in `lib`, 
how do I handle my `css` files?

it doesn't copy over the css files, 
it keeps ` require(".styles.css") ` as is which results in an error. 

it's worth noting that `-- --copy-files` does nothing to the css files.

**Comment by lsmoura** [comment]
a plain `nwb` created project does not simply _copy_ the css files. it bundles and minifies them. If you're using `import 'file-name-here.css';` or `require('file-name-here.css');` it will render the same output: `dist/app.hash.css`.

Have you changed anything on your nwb config files?

No `require` function should exist on the final bundled `dist/app.hash.js` file.
