### ISSUE TITLE
Misc ideas

### ISSUE THREAD

**Issue by insin** [insin/nwb#5]
- Investigate/configure rewire for tests
- Enable running of the user's own lint setup - e.g. check for a `lint` script in npm run and run it, or let them configure something in the config file.
- Offer a selection of Karma testing framework/assertion library options when running `new` and install and configure them for the user
- Is there a clean way to extract the React-specific pieces out?
  - what if project types were implemented as plugins, registering
    - a project  `type` for which they can handle or provide additional configuration for `new`, `clean`, `build`, `serve` and `test` commands
    - new top-level commands
- Other plugin types?

**Comment by insin** [comment]
How about being able to specify an HTML file and an entry point, parsing it and generating a Webpack config from it, sort of like a cross between https://github.com/substack/html-inline and webpack/webpack#536?

**Comment by andreypopp** [comment]
I'm interested in adding linting to webpack workflow. One of the idea I have and partially implemented (see https://github.com/andreypopp/prefetch-context-webpack-plugin) is to reuse webpack cached/watched fs and run elsint against it.

Then it would be cool to expose lint diagnostic messages via some interface (CLI , TCP) so IDEs (vim also) could you them.
