### ISSUE TITLE
does this create a git repo?

### ISSUE THREAD

**Issue by AndyOGo** [insin/nwb#505]
This issue is a: 

- Question / support request

I did [`nwb new web-module my-module`](https://github.com/insin/nwb#npm-modules-for-the-web) and got an unexpected `.git/` repo.

Is this intended, if so why?
Can I disable it?

Btw. I use lernaJS too

**Comment by lsmoura** [comment]
If you really don't want your new project to be a git repo, you can just delete the `.git` folder, and probably the `.gitignore` file as well.

**Comment by AndyOGo** [comment]
@Ismoura
Thank you for your answer.

Yeah, that's correct. In fact that is what I did, just delete `.git/` folder.
But I would really rather like to have it as an opt-in option 🙏 

May I ask where this behaviour is documented, I couldn't find it at a first glance?

**Comment by lsmoura** [comment]
@AndyOGo Check my comment on [this thread](https://github.com/insin/nwb/issues/484). You can entirely disable the creation of the git repo.

**Comment by AndyOGo** [comment]
@lsmoura 
haha, thanks a lot, nice to chat with you
