### ISSUE TITLE
Functionality to extend nwb commands

### ISSUE THREAD

**Issue by trueadm** [insin/nwb#51]
Hey, great work on nwb @insin,

Is it possible to add custom commands via `nwb.config.js` into an app? Maybe if there was a way to specify what a custom command would call or do as some kind of extension/transformer. The reason I ask is because I'd love it there was some way of performing linting checks/fixes and a `build` where the output is minified. Also being able to specify a custom project template when using `new` and `init` would be great.

**Comment by insin** [comment]
> I'd love it there was some way of performing linting checks/fixes

Do you have an example of how you'd llike to use this?

e.g. I currently manually install [my own ESLint setup](https://github.com/insin/eslint-config-jonnybuchanan) then tweak my package.json scripts like this...
```js
  "scripts": {
    "build": "npm run lint && nwb test",
    "lint": "eslint src test",
    "test": "nwb build && nwb test"
  },
```
...but I'd like to get more examples of how people are linting stuff before adding something which tries to call your linting setup to nwb.

This is something I want to do eventually anyway, as called out in the docs: https://github.com/insin/nwb/blob/master/docs/Introduction.md#not-currently-considered

> a `build` where the output is minified

Which type of project is this for, and which built files?

Only the `lib/` and `es6/` builds and one of the `umd/` build files in npm module projects should be unminified at the moment.

> Also being able to specify a custom project template when using `new` and `init` would be great.

Technically, this should just be a case of letting you configure the directory which gets copied by [copy-template-dir](https://github.com/yoshuawuyts/copy-template-dir).

Do you have an example of a custom template you'd like to use so I can try something out with it?

**Comment by viniciusbo** [comment]
I ended up adding some new build steps to `package.json` for bundling and editing `build` step:

```json
{
  "scripts": {
    "bundle:js": "babel --presets es2015 --plugins transform-react-jsx src/**/*.js | uglifyjs -c > dist/bundle.js",
    "bundle:css": "cleancss src/css/* --skip-rebase > dist/bundle.css",
    "build": "nwb build && npm run bundle:js && npm run bundle:css"
  }
}
```

What do you guys think about that? Is there any better way of doing this?

**Comment by insin** [comment]
That's what I'm doing in the apps I use nwb in at work, just calling `nwb` in npm scripts for the client build and writing other scripts as usual for everything else.

**Comment by insin** [comment]
Closing this as there are no plans to extend commands right now - use npm scripts.
