### ISSUE TITLE
how can sass be inline with the bundle instead of in a css file?

### ISSUE THREAD

**Issue by bakedbean** [insin/nwb#518]
This issue is a:
- Question / support request

I'm using the latest version of nwb to build a standalone npm module.

I would like to import sass, and have it inline with the js bundle, as opposed to in a separate stylesheet.
I'm using nwb-sass.

I have this in my config:
```
module: {
    rules: [{
      'sass-css': {
        modules: true,
        localIdentName: '[hash:base64:5]'
      }
    }]
  }
```

This creates a separate css file from the imported sass just fine, but I can't seem to find anything that describes how to have it inline with the bundle?

Any help is appreciated.

**Comment by insin** [comment]
Does setting [`webpack.extractCSS` config](https://github.com/insin/nwb/blob/master/docs/Configuration.md#extractcss-object--false) to `false` do what you want?

**Comment by bakedbean** [comment]
Yes that was the answer, I meant to come back here and post that and forgot, thanks for the followup
