### ISSUE TITLE
devServer.host is ignored in config

### ISSUE THREAD

**Issue by adriancmiranda** [insin/nwb#524]
This issue is a: 

- Bug report

I'd think that [webpackServer.js#L86](https://github.com/insin/nwb/blob/master/src/webpackServer.js#L86) should be:

```js
let url = `http${serverConfig.https ? 's' : ''}://${serverConfig.host || 'localhost'}:${port}/`
```

just as it's with the `https` property

```js
module.exports = {
	devServer: {
		https: true,
		host: '0.0.0.0',
        },
}
```

**Comment by insin** [comment]
Looks like you're right, thanks for the report 👍
