### ISSUE TITLE
terminal clearing so fast it is impossible to see nwb generated messages

### ISSUE THREAD

**Issue by tnrich** [insin/nwb#526]
Hey @insin ,

I'm finding that starting my nwb app I'm seeing a flash of comments:

![image](https://user-images.githubusercontent.com/2730609/55427782-981dcf80-553c-11e9-8eca-68f4f38c680a.png)

which rapidly get covered up by the terminal clearing: 

![image](https://user-images.githubusercontent.com/2730609/55427808-a835af00-553c-11e9-9c97-8a7545d222c9.png)
  
I had to record the terminal just to get those screenshots. 

Any thoughts on this?
Thanks!

**Comment by insin** [comment]
If you want to view the config report separately, you can run `nwb check-config`.

To disable clearing the console you can pass a `--no-clear` flag, like `nwb serve --no-clear` when running nwb directly or `npm start -- --no-clear` when running via a package manager.
