### ISSUE TITLE
Uncaught TypeError: Found non-callable @@iterator after upgrading from 24 -> 25

### ISSUE THREAD

**Issue by tnrich** [insin/nwb#552]
After upgrading to v25 I started to get errors on this code: 
```js
let result = getXStartAndWidthOfRangeWrtRow(
    row,
    row,
    bpsPerRow,
    charWidth,
    sequenceLength,
    ...(getGaps ? [getGaps(row).gapsBefore, getGaps(row).gapsInside] : [])
  );
```

```
Uncaught TypeError: Found non-callable @@iterator
```

I would imagine nwb should still patch the argument spread functionality as it doesn't seem to be supported on the latest version of chrome (83) yet? 

Any thoughts on this @insin ? 

Thanks!

**Comment by insin** [comment]
Chrome supports it, but this is what happens if you try to spread a non-iterable into a function call:

```
> console.log(...{})
VM102:1 Uncaught TypeError: Found non-callable @@iterator
    at <anonymous>:1:9
```

You're ensuring it's an array being spread, so is it definitely this code?

**Comment by tnrich** [comment]
Thanks for the reply @insin I'll look more into it. I believe it is this code but am not 100% sure
