### ISSUE TITLE
Allow users to put nwb.config.js in package.json

### ISSUE THREAD

**Issue by sotojuan** [insin/nwb#60]
For example, Babel [allows](https://babeljs.io/docs/usage/babelrc/#use-via-package-json) you to put `.babelrc` contents in your package.json.

There are modules that let you read from package.json, so this would not be hard at all to implement and would result in one less config file.

If you agree, let me know. I'm open to implementing it.

**Comment by insin** [comment]
This won't work for certain types of config (karma plugins, extra webpack plugins, top-level config like nib for Stylus), but I'll have a look at how fiddly it would be to add.

**Comment by sotojuan** [comment]
Got it, it was just a suggestion. I'm working on a toy project and using `nwb` and I just have `'react-app'` on mine so I thought it'd be nice to just put that in package.json.

**Comment by insin** [comment]
If you don't need any other config, the next version will allow you to skip providing a config file altogether if you use the react-app specific commands directly (documentation TBD!)

**Comment by insin** [comment]
Not planning to do this now.
