### ISSUE TITLE
ERROR in ./src/index.js Module build failed: ReferenceError: [BABEL] 

### ISSUE THREAD

**Issue by dmitriz** [insin/nwb#62]
After `nwb new web-app test-app`, 
trying

``` sh
$ nwb serve
```

or 

``` sh
$ nwb serve --auto-install
```

and getting:

``` sh
...
ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Volumes/Macintosh HD/Users/dmitrizaitsev/Dropbox/Sandbox/nwb-web-app/src/index.js: Unknown option: /Volumes/Macintosh HD/Users/dmitrizaitsev/Dropbox/Sandbox/.babelrc.presets
...
```

**Comment by brumm** [comment]
You seem to have a .babelrc file at `~/Dropbox/Sandbox/.babelrc`, containing a `presets` key, which is new to babel 6 and not recognized by babel 5.

**Comment by dmitriz** [comment]
Thanks, I'm really surprised it looked up the tree, given the answers from one of babel's maintainers: https://www.reddit.com/r/javascript/comments/40pag0/the_sad_state_of_entitled_web_developers/cyw9hi9

Seems to work now but still a bunch of files not found inside `build` folder that was never created.
