### ISSUE TITLE
Make it possible to add any extra webpack config

### ISSUE THREAD

**Issue by insin** [insin/nwb#65]
As it currently stands, 0.8 will have `webpack.loaders.extra` and `webpack.plugins.extra` - what if we just had a single `webpack.extra` config which gets merged into the generated config?

I'm finding I commonly want to setup aliases for top-level directories (like a single `src/images/` dir which can be referenced from any module just by using `require('images/blah.png')`).

**Comment by geowarin** [comment]
Why not supporting the babel-plugin-module-alias out of the box with an alias property?

```
alias: {
   'images': './src/images'
}
```

**Comment by insin** [comment]
No particular reason, I didn't know that plugin existed, but would prefer to use the built-in feature of Webpack.

**Comment by geowarin** [comment]
The reason I tend to use the babel plugin is that it will also work in tests.
Before #41, it was not possible to use the plugin I think. I will give it a shot now.
