### ISSUE TITLE
Consistently use namespace objects in config - breaking change

### ISSUE THREAD

**Issue by insin** [insin/nwb#7]
Make this only take up one namespace slot in the config object.

Before - set `umd` to `false` to disable:
```js
{
  umd: true,
  global: 'Blah',
  externals: {
    foo: 'Foo'
  }
}
```

After - omit `umd` or set it to 'false' to disable
```js
{
  umd: {
    global: 'Blah',
    externals: {
      foo: 'Foo'
    }
  }
}
```

Technically a simple change, but it's made fiddly by [copy-template-dir](https://github.com/yoshuawuyts/copy-template-dir) only supportting replacement of `{{blah}}` variables, so we might need to look for something else.

We'll keep backwards compatibility with the old format plus warning messages in 0.2 and remove it in the following release.

**Comment by insin** [comment]
Should we also do this with webpack config for consistency? I'd like it if plugin support could just be a deep merge of a config object!

Before:
```js
{
  define: {
  },
  loaders: {
    //...
    extra: [
    ]
  }
}
```
After:
```js
{
  webpack: {
    define: {
    },
    loaders: {
      //...
      extra: [
      ]
    }
  }
}
```

**Comment by bebraw** [comment]
Maybe [webpack-merge](https://www.npmjs.com/package/webpack-merge) would work for your use case? It allows you to extend configuration (arrays/objects) in a logical manner. I've used this scheme in Antwar and it works quite nicely. It also cuts down special logic from your side altogether once you understand the rule.

**Comment by insin** [comment]
I have one eye on webpack-merge until I've figured out exactly what we need - e.g. would we ever need to be able to replace lists instead of appending, or pass null or some sentinel to indicate a property should be deleted, or even just  being able pass an update spec like react-addons-update.

**Comment by bebraw** [comment]
@insin Good point! Before extending webpack-merge I will want to see a concrete use case to warrant the feature. But let's keep an eye on this. :+1:

**Comment by insin** [comment]
On second thoughts, using a boolean for `umd` lets us keep and document all the options for optional features in the default config file, should someone change their mind later.
