### ISSUE TITLE
Allow setting `devtool` value in config

### ISSUE THREAD

**Issue by jfaissolle** [insin/nwb#71]
Hello, I am encountering a problem for debugging in chrome (see https://github.com/webpack/webpack/issues/740). To work around this problem I wanted to change the value to "#inline-source-map".
I couldn't find how to set the `devtool` config value. From the code it seems that the user supplied value is ignored.

It would be really appreciated to be able to set this value in the config file.

Thanks

**Comment by insin** [comment]
As of v0.8, you can provide [`webpack.extra` config](https://github.com/insin/nwb/blob/788dd5d9cfe9d690ff69cb9ca18e9f7ecb6994d7/docs/Configuration.md#extra-object) in `nwb.config.js` which will get merged on top of the webpack configuration nwb creates:

```js
module.exports = {
  // ...
  webpack: {
    extra: {
      devtool: '#inline-source-map'
    }
  }
```

**Comment by jfaissolle** [comment]
Great ! Thanks a lot !
