### ISSUE TITLE
Suggestion for adding styles to demo html?

### ISSUE THREAD

**Issue by bpugh** [insin/nwb#72]
I'm in the process of updating https://github.com/insin/react-maskedinput/blob/master/demo/index.html
to follow nwb's convention for creating a demo page and while it was really straightforward to get working, the only issue I've run into is including the styles for the demo.
I considered just doing inline styles but it seems like that would clutter up the demo too much. Not sure if I'm not thinking of something obvious but I would also be happy to submit a PR to make the demo template more customizable. Thoughts?

**Comment by insin** [comment]
You can import CSS to have Webpack manage it: e.g. https://github.com/insin/react-router-form/tree/master/demo/src

**Comment by bpugh** [comment]
Thanks! That works. Sorry for the obvious question. Closing.
