### ISSUE TITLE
What does nwb stand for?

### ISSUE THREAD

**Issue by hackingbeauty** [insin/nwb#74]
Just curious.  It's not clarified in the README.

**Comment by timrnz** [comment]
`Newb`?

> A term used to describe a inexperienced gamer/person/etc. Unlike a noob, a newb is someone who actually wants to get better.

**Comment by insin** [comment]
Officially: nothing, it's now just a three letter command which is easy to type.

The "n" used to be "npm", but I didn't think it would be ok to use the name of another product as part of its name.
