### ISSUE TITLE
auto-install does not seem to work with npm packages with dots in their name

### ISSUE THREAD

**Issue by Fenntasy** [insin/nwb#77]
for instance 

```javascript
import times from 'lodash.times'
```
will not attempt to install lodash.times and so will trigger an error with webpack
```
ERROR in ./src/App.js
Module not found: Error: Cannot resolve module 'lodash.times' in ...
```
I assume this is due to the dot in the name of the package and not a problem with this specific package (I tried with lodash.random and lodash.times with the same result but I don't know other packages that uses the dot in the name).

**Comment by Fenntasy** [comment]
I was just researching on my own but you're quick :p

It doesn't work with v3 of the plugin? I'm not sure how to test it on my own but the match query from the v3:
```javascript
var matches = /Cannot resolve module '([@\w\/\.-]+)' in/.exec(err);
```
should work with period (I tested the regex).

**Comment by insin** [comment]
There's another check in `installer.js` which modules with periods in their names won't pass.
