### ISSUE TITLE
NWB Installing npm package instead of using local directory

### ISSUE THREAD

**Issue by ap13p** [insin/nwb#83]
node -v # v4.3.2
npm -v # 3.8.1
nwb -v # 0.8.1

Let say I have the following directory structure

```
+ src
|-- components
|  | counter.jsx
```

And my nwb.config.js
```
'use strict';
const path = require('path');

module.exports = {
    type: 'react-app',
    webpack: {
        extra: {
            resolve: {
                root: [
                    path.resolve(path.join(__dirname, './src/')),
                ],
            },
        },
    },
}
```

My App.js
```
import Counter from 'components/counter';
```
Instead of using local directory which is /src/components nwb install a npm package called components.

**Comment by insin** [comment]
This won't work in nwb 0.8.1, as it uses npm-install-webpack-plugin@2 , which doesn't support `resolve` config.

I've checked that it works in the upcoming version of nwb, which uses npm-install-webpack-plugin@3 - you'll have to avoid the `--auto-install` flag until then if you want to use `resolve`.

**Comment by ap13p** [comment]
Nice! Thanks.

**Comment by insin** [comment]
It'll auto-close when 0.9 is merged into `master`
