### ISSUE TITLE
Custom HTML for react-component demo

### ISSUE THREAD

**Issue by joshwcomeau** [insin/nwb#87]
I'm creating a React component, and I'd like for its demo to be a pretty full-featured demo app.

By default, there is no index.html file in the /demo/src directory. When I run `nwb build`, a template gets built that automatically links up the compiled JS/CSS.

This is awesome! But I need to have some custom stuff added to that index.html file (custom `<title>`, a `<link>` for my Google Fonts stylesheet, etc).

Right now I'm just manually pasting it into the /demo/dist/index.html file, but that feels really messy.

In [the introduction](https://github.com/insin/nwb/blob/master/docs/Introduction.md#not-configurable-yet), it implies I can use a template HTML file if I have an `index.html` file in `/src`. I have tried using it without success... `nwb build` seems to be ignoring it.

Would appreciate any guidance in figuring out how to do this in a nicer way. Absolutely loving nwb so far :)

**Comment by insin** [comment]
Demo app builds currently set to use a default, basic template: https://github.com/insin/nwb/blob/5c0671b102e542e384e1ba41b6d64e05be2dfc48/src/createWebpackConfig.js#L316

It wouldn't take much to have demo builds check for `demo/src/index.html` (in keeping with the `src/index.html` convention for React/web apps) and use that instead if present.

**Comment by insin** [comment]
This wasn't intended, but adding `webpack.plugins.html.template` config to your `nwb.config.js` which points to your custom demo template might just work.

**Comment by joshwcomeau** [comment]
Awesome, thanks @insin! Will try that.

**Comment by varandpez** [comment]
This is great for having external HTML... 
I'm trying to add external css/js files (bootstrap framework FYI) to the template html. seems like it doesn't get picked by nwb.

Any suggestion on how to add css frameworks?

Thanks.

**Comment by revolunet** [comment]
Looks like we must **not** include the `plugins` key in `nwb.config.js`.

Works for me : 

```js
module.exports = {
  type: 'react-component',
  npm: {
    esModules: true,
    umd: false
  },
  webpack: {
    html: {
      template: 'src/index.html'
    }
  }
}
```

**Comment by insin** [comment]
Plugin config was moved up to the top-level `webpack` object a while back for convenience - thanks for the example solution.

**Comment by jimniels** [comment]
FWIW, I had to specify the `demo` folder in my config to get this to work (nwb version `0.20.0`), i.e.

```js
module.exports = {
  webpack: {
    html: {
      template: 'demo/src/index.html'
    }
  }
}
```
