### ISSUE TITLE
Plans for supporting custom templates

### ISSUE THREAD

**Issue by cafreeman** [insin/nwb#88]
I was wondering if you had any input on the best path for using `nwb` to implement a custom template. Is it worth trying to actually build a new project type and submit a PR or something? Is there a more modular way to just build a custom template for use with `nwb`?

Or, ultimately, am I better of just making yeoman generator or something that uses regular `nwb` once everything else has been scaffolded?

**Comment by cafreeman** [comment]
To be clear, if there's work I can do to help support an existing effort to allow for custom templates, I'm happy to help out if someone can point me in the right direction.

**Comment by insin** [comment]
You're probably safer doing this outside of `nwb`, just using it in `devDependencies` and `scripts` - the project templates are there solely to provide a workflow for getting started quickly with entry points in the right place, they're not really the main point of nwb.
