### ISSUE TITLE
Styling the demo page

### ISSUE THREAD

**Issue by hackingbeauty** [insin/nwb#91]
Hey, I'm using the following command to build the demo page for my component:

```
nwb build-demo
```

Everything works; however, I need to style my demo page.  

How can I add styles so that when I run the build-demo command my styles are included in the /dist folder?

Great tool btw.  Love nwb.

**Comment by insin** [comment]
Duplicate of #72

**Comment by jorrit** [comment]
CSS modules don't work out of the box for me, did you add something to webpack @novascreen ?

**Comment by novascreen** [comment]
@jorrit yes, modules need to be enabled in the config:
https://github.com/novascreen/react-columns/blob/master/nwb.config.js
