### ISSUE TITLE
What Babel stage is being used behind the scene? 

### ISSUE THREAD

**Issue by varandpez** [insin/nwb#93]
Hi,

First, thanks for this great tool...
I have issues binding propTypes to my class. I'm using es7 syntax and do
`static propTypes: {}`

My question is what stage of babelify is used behind the engine and how can I modify it?

Thanks.

**Comment by calebmer** [comment]
Did you mean `static propTypes = {}` (with `=`, not `:`).

Disclaimer: not a core team member.

**Comment by varandpez** [comment]
With `=` I'm getting build error...
`Unexpected token (4:19)

export default class extends React.Component {
  static propTypes = {
    components: React.PropTypes.array.isRequired,
    events: React.PropTypes.array.isRequired,
  } `

**Comment by geowarin** [comment]
You can change the babel stage [in nwb.config.js](https://github.com/insin/nwb/blob/master/docs/Configuration.md#babel-configuration)

**Comment by varandpez** [comment]
This can be closed... Babel stage is configurable from nwb.config.js file.
💭
