### ISSUE TITLE
React Hot Loader 3

### ISSUE THREAD

**Issue by insin** [insin/nwb#99]
https://github.com/gaearon/react-hot-loader/pull/240

**Comment by tomitrescak** [comment]
Hi, any progress on this? I would love to have this working. Would be fantastic;) I know there Is a bit more configuration around v3, but totally worth it;)

**Comment by codeart1st** [comment]
Yeah support for pure components would be really nice

**Comment by insin** [comment]
Superseded by React Fast Refresh
